# Лабораторная работа №8

## Скрапинг и анализ текста

**Выполнил:** Корнеев Фёдор, группа P3120

Цель работы — собрать новости с сайта ITMO.NEWS, сохранить общую информацию о публикациях, а затем получить подробные данные для каждой новости: заголовок, дату, количество просмотров, текст и теги.

## 1. Импорт библиотек

Для загрузки страниц используется `requests`, для разбора HTML — `BeautifulSoup`, а для хранения и сохранения результатов — `pandas`.

Во время тестирования используется ограниченный набор страниц. После проверки парсера тестовый режим будет отключён.

In [1]:
import re
import time
from pathlib import Path
from urllib.parse import urljoin

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm.auto import tqdm

BASE_URL = "https://news.itmo.ru"
MAIN_NEWS_URL = BASE_URL + "/ru/main_news/{page}/"

OUTPUT_DIR = Path("news_content")
OUTPUT_DIR.mkdir(exist_ok=True)

GENERAL_CSV = Path("news.csv")
CONTENT_CSV = OUTPUT_DIR / "news_content.csv"

# Этап проверки:
# полный индекс новостей собираем со всех страниц,
# но содержимое пока проверяем только на 3 статьях.
FULL_LISTING = True
FULL_CONTENT = True

TEST_PAGES = 2
TEST_ARTICLES = 10

REQUEST_DELAY = 0.25
REQUEST_TIMEOUT = 30

print("Полный список новостей:", FULL_LISTING)
print("Полный парсинг содержимого:", FULL_CONTENT)
print("Общий CSV:", GENERAL_CSV)
print("CSV с содержимым:", CONTENT_CSV)

Полный список новостей: True
Полный парсинг содержимого: True
Общий CSV: news.csv
CSV с содержимым: news_content/news_content.csv

/Users/infinitrator/infinitrator.github.io/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. HTTP-сессия и вспомогательные функции

Используется одна `requests.Session`, чтобы не создавать новое соединение для каждого запроса. Также задаётся обычный браузерный `User-Agent`.

In [2]:
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


session = requests.Session()

session.headers.update({
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 "
        "Chrome/140.0 Safari/537.36"
    )
})

retry = Retry(
    total=4,
    connect=4,
    read=4,
    status=4,
    backoff_factor=0.5,
    status_forcelist=(429, 500, 502, 503, 504),
    allowed_methods=frozenset({"GET"}),
    raise_on_status=False,
)

adapter = HTTPAdapter(max_retries=retry)

session.mount("https://", adapter)
session.mount("http://", adapter)


def clean_text(value):
    """Удаляет лишние пробелы из текста."""
    if value is None:
        return None

    return " ".join(str(value).split())


def get_soup(url):
    """Загружает HTML-страницу и возвращает BeautifulSoup."""
    response = session.get(url, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    return BeautifulSoup(response.text, "html.parser")

## 3. Парсинг страницы со списком новостей

Для каждой новости из общего списка собираются:

- идентификатор новости;
- название;
- дата размещения;
- URL.

Идентификатор извлекается из URL вида `/news/15033/`.

In [3]:
NEWS_ID_RE = re.compile(r"/news/(\d+)/?")


def parse_listing_page(page_number):
    url = MAIN_NEWS_URL.format(page=page_number)
    soup = get_soup(url)

    result = []

    for item in soup.select("ul.triplet > li"):
        # У карточки новости может быть несколько ссылок:
        # картинка с пустым текстом и отдельная ссылка-заголовок.
        news_links = []

        for link in item.find_all("a", href=True):
            href = link.get("href", "")

            if NEWS_ID_RE.search(href):
                news_links.append(link)

        if not news_links:
            continue

        link = news_links[0]
        href = link.get("href", "")

        match = NEWS_ID_RE.search(href)

        if match is None:
            continue

        news_id = int(match.group(1))

        # Сначала пытаемся найти непустую текстовую ссылку
        # на ту же новость.
        title = None

        for candidate in news_links:
            candidate_text = clean_text(
                candidate.get_text(" ", strip=True)
            )

            if candidate_text:
                title = candidate_text
                break

        # Резервный вариант на случай другой верстки.
        if not title:
            heading = item.find(["h2", "h3", "h4"])

            if heading is not None:
                title = clean_text(
                    heading.get_text(" ", strip=True)
                )

        if not title:
            continue

        time_tag = item.find("time")

        if time_tag is None:
            continue

        date = (
            time_tag.get("datetime")
            or clean_text(time_tag.get_text(" ", strip=True))
        )

        news_url = urljoin(BASE_URL, href)

        result.append({
            "id": news_id,
            "title": title,
            "date": date,
            "url": news_url,
        })

    # На всякий случай исключаем повтор одной и той же новости,
    # если HTML содержит несколько одинаковых карточек.
    unique = {}

    for row in result:
        unique[row["id"]] = row

    result = list(unique.values())

    next_link = None

    for link in soup.select("div.pagination a"):
        if clean_text(link.get_text()) == "Следующая":
            next_link = link
            break

    has_next = bool(
        next_link
        and next_link.get("href")
        and next_link.get("href") != "#"
        and "disabled" not in next_link.get("class", [])
    )

    return result, has_next


test_rows, test_has_next = parse_listing_page(1)

print("Новостей на первой странице:", len(test_rows))
print("Есть следующая страница:", test_has_next)

pd.DataFrame(test_rows)

Новостей на первой странице: 9
Есть следующая страница: True

,id,title,date,url
0,15033,Соединили пышки и квантовую механику: как ИТМО...,2026-09-21T18:24:25,https://news.itmo.ru/ru/education/cooperation/...
1,15018,Эра сверхбыстрых вычислений: в ИТМО появился И...,2026-09-15T16:40:38,https://news.itmo.ru/ru/science/photonics/news...
2,15003,Олимпиадный год: итоги самой масштабной приемн...,2026-09-01T19:18:10,https://news.itmo.ru/ru/education/official/new...
3,15001,ITMO CONF 2026: как идеи проходят путь от лабо...,2026-08-31T18:44:11,https://news.itmo.ru/ru/education/trend/news/1...
4,14985,Всем по киберпышке! ИТМО и Яндекс Образование ...,2026-08-18T15:57:07,https://news.itmo.ru/ru/education/cooperation/...
5,14984,Российские школьники взяли четыре медали на Ме...,2026-08-17T16:39:54,https://news.itmo.ru/ru/university_live/achiev...
6,14973,В ИТМО завершили прием на бюджет бакалавриата:...,2026-08-07T14:20:30,https://news.itmo.ru/ru/education/trend/news/1...
7,14967,Студенты ИТМО заняли пять призовых мест на меж...,2026-08-05T16:14:12,https://news.itmo.ru/ru/university_live/achiev...
8,14944,"За дипломом, на сапы и в научный бар. Каким бы...",2026-07-20T16:25:07,https://news.itmo.ru/ru/university_live/leisur...

## 4. Сбор общего списка новостей

Парсер последовательно проходит страницы раздела `main_news`.

В тестовом режиме обрабатываются только первые две страницы. При полном запуске страницы обходятся до исчезновения кнопки «Следующая».

In [4]:
all_news = []

page = 1

while True:
    rows, has_next = parse_listing_page(page)

    if not rows:
        raise RuntimeError(
            f"На странице {page} не найдено ни одной новости: "
            f"{MAIN_NEWS_URL.format(page=page)}"
        )

    all_news.extend(rows)

    print(
        f"Страница {page}: "
        f"{len(rows)} новостей, "
        f"всего собрано {len(all_news)}"
    )

    if not FULL_LISTING and page >= TEST_PAGES:
        break

    if not has_next:
        break

    page += 1
    time.sleep(REQUEST_DELAY)


news_df = pd.DataFrame(
    all_news,
    columns=["id", "title", "date", "url"]
)

news_df = (
    news_df
    .drop_duplicates(subset="id")
    .sort_values("id", ascending=False)
    .reset_index(drop=True)
)

print()
print("Последняя обработанная страница:", page)
print("Итого уникальных новостей:", len(news_df))

news_df.head(10)

Страница 1: 9 новостей, всего собрано 9

Страница 2: 9 новостей, всего собрано 18

Страница 3: 9 новостей, всего собрано 27

Страница 4: 9 новостей, всего собрано 36

Страница 5: 9 новостей, всего собрано 45

Страница 6: 9 новостей, всего собрано 54

Страница 7: 9 новостей, всего собрано 63

Страница 8: 9 новостей, всего собрано 72

Страница 9: 9 новостей, всего собрано 81

Страница 10: 9 новостей, всего собрано 90

Страница 11: 9 новостей, всего собрано 99

Страница 12: 9 новостей, всего собрано 108

Страница 13: 9 новостей, всего собрано 117

Страница 14: 9 новостей, всего собрано 126

Страница 15: 9 новостей, всего собрано 135

Страница 16: 9 новостей, всего собрано 144

Страница 17: 9 новостей, всего собрано 153

Страница 18: 9 новостей, всего собрано 162

Страница 19: 9 новостей, всего собрано 171

Страница 20: 9 новостей, всего собрано 180

Страница 21: 9 новостей, всего собрано 189

Страница 22: 9 новостей, всего собрано 198

Страница 23: 9 новостей, всего собрано 207

Страница 24: 9 новостей, всего собрано 216

Страница 25: 9 новостей, всего собрано 225

Страница 26: 9 новостей, всего собрано 234

Страница 27: 9 новостей, всего собрано 243

Страница 28: 9 новостей, всего собрано 252

Страница 29: 9 новостей, всего собрано 261

Страница 30: 9 новостей, всего собрано 270

Страница 31: 9 новостей, всего собрано 279

Страница 32: 9 новостей, всего собрано 288

Страница 33: 9 новостей, всего собрано 297

Страница 34: 9 новостей, всего собрано 306

Страница 35: 9 новостей, всего собрано 315

Страница 36: 9 новостей, всего собрано 324

Страница 37: 9 новостей, всего собрано 333

Страница 38: 9 новостей, всего собрано 342

Страница 39: 9 новостей, всего собрано 351

Страница 40: 9 новостей, всего собрано 360

Страница 41: 9 новостей, всего собрано 369

Страница 42: 9 новостей, всего собрано 378

Страница 43: 9 новостей, всего собрано 387

Страница 44: 9 новостей, всего собрано 396

Страница 45: 9 новостей, всего собрано 405

Страница 46: 9 новостей, всего собрано 414

Страница 47: 9 новостей, всего собрано 423

Страница 48: 9 новостей, всего собрано 432

Страница 49: 9 новостей, всего собрано 441

Страница 50: 9 новостей, всего собрано 450

Страница 51: 9 новостей, всего собрано 459

Страница 52: 9 новостей, всего собрано 468

Страница 53: 9 новостей, всего собрано 477

Страница 54: 9 новостей, всего собрано 486

Страница 55: 9 новостей, всего собрано 495

Страница 56: 9 новостей, всего собрано 504

Страница 57: 9 новостей, всего собрано 513

Страница 58: 9 новостей, всего собрано 522

Страница 59: 9 новостей, всего собрано 531

Страница 60: 9 новостей, всего собрано 540

Страница 61: 9 новостей, всего собрано 549

Страница 62: 9 новостей, всего собрано 558

Страница 63: 9 новостей, всего собрано 567

Страница 64: 9 новостей, всего собрано 576

Страница 65: 9 новостей, всего собрано 585

Страница 66: 9 новостей, всего собрано 594

Страница 67: 9 новостей, всего собрано 603

Страница 68: 9 новостей, всего собрано 612

Страница 69: 9 новостей, всего собрано 621

Страница 70: 9 новостей, всего собрано 630

Страница 71: 9 новостей, всего собрано 639

Страница 72: 9 новостей, всего собрано 648

Страница 73: 9 новостей, всего собрано 657

Страница 74: 9 новостей, всего собрано 666

Страница 75: 9 новостей, всего собрано 675

Страница 76: 9 новостей, всего собрано 684

Страница 77: 9 новостей, всего собрано 693

Страница 78: 9 новостей, всего собрано 702

Страница 79: 9 новостей, всего собрано 711

Страница 80: 9 новостей, всего собрано 720

Страница 81: 9 новостей, всего собрано 729

Страница 82: 9 новостей, всего собрано 738

Страница 83: 9 новостей, всего собрано 747

Страница 84: 9 новостей, всего собрано 756

Страница 85: 9 новостей, всего собрано 765

Страница 86: 9 новостей, всего собрано 774

Страница 87: 9 новостей, всего собрано 783

Страница 88: 9 новостей, всего собрано 792

Страница 89: 9 новостей, всего собрано 801

Страница 90: 9 новостей, всего собрано 810

Страница 91: 9 новостей, всего собрано 819

Страница 92: 9 новостей, всего собрано 828

Страница 93: 9 новостей, всего собрано 837

Страница 94: 9 новостей, всего собрано 846

Страница 95: 9 новостей, всего собрано 855

Страница 96: 9 новостей, всего собрано 864

Страница 97: 9 новостей, всего собрано 873

Страница 98: 9 новостей, всего собрано 882

Страница 99: 9 новостей, всего собрано 891

Страница 100: 9 новостей, всего собрано 900

Страница 101: 9 новостей, всего собрано 909

Страница 102: 9 новостей, всего собрано 918

Страница 103: 9 новостей, всего собрано 927

Страница 104: 9 новостей, всего собрано 936

Страница 105: 9 новостей, всего собрано 945

Страница 106: 9 новостей, всего собрано 954

Страница 107: 9 новостей, всего собрано 963

Страница 108: 9 новостей, всего собрано 972

Страница 109: 9 новостей, всего собрано 981

Страница 110: 9 новостей, всего собрано 990

Страница 111: 9 новостей, всего собрано 999

Страница 112: 9 новостей, всего собрано 1008

Страница 113: 9 новостей, всего собрано 1017

Страница 114: 9 новостей, всего собрано 1026

Страница 115: 9 новостей, всего собрано 1035

Страница 116: 9 новостей, всего собрано 1044

Страница 117: 9 новостей, всего собрано 1053

Страница 118: 9 новостей, всего собрано 1062

Страница 119: 9 новостей, всего собрано 1071

Страница 120: 9 новостей, всего собрано 1080

Страница 121: 9 новостей, всего собрано 1089

Страница 122: 9 новостей, всего собрано 1098

Страница 123: 9 новостей, всего собрано 1107

Страница 124: 9 новостей, всего собрано 1116

Страница 125: 9 новостей, всего собрано 1125

Страница 126: 9 новостей, всего собрано 1134

Страница 127: 9 новостей, всего собрано 1143

Страница 128: 4 новостей, всего собрано 1147

Последняя обработанная страница: 128
Итого уникальных новостей: 1147

,id,title,date,url
0,15033,Соединили пышки и квантовую механику: как ИТМО...,2026-09-21T18:24:25,https://news.itmo.ru/ru/education/cooperation/...
1,15018,Эра сверхбыстрых вычислений: в ИТМО появился И...,2026-09-15T16:40:38,https://news.itmo.ru/ru/science/photonics/news...
2,15003,Олимпиадный год: итоги самой масштабной приемн...,2026-09-01T19:18:10,https://news.itmo.ru/ru/education/official/new...
3,15001,ITMO CONF 2026: как идеи проходят путь от лабо...,2026-08-31T18:44:11,https://news.itmo.ru/ru/education/trend/news/1...
4,14985,Всем по киберпышке! ИТМО и Яндекс Образование ...,2026-08-18T15:57:07,https://news.itmo.ru/ru/education/cooperation/...
5,14984,Российские школьники взяли четыре медали на Ме...,2026-08-17T16:39:54,https://news.itmo.ru/ru/university_live/achiev...
6,14973,В ИТМО завершили прием на бюджет бакалавриата:...,2026-08-07T14:20:30,https://news.itmo.ru/ru/education/trend/news/1...
7,14967,Студенты ИТМО заняли пять призовых мест на меж...,2026-08-05T16:14:12,https://news.itmo.ru/ru/university_live/achiev...
8,14944,"За дипломом, на сапы и в научный бар. Каким бы...",2026-07-20T16:25:07,https://news.itmo.ru/ru/university_live/leisur...
9,14916,ИТМО получит 196 миллионов рублей на развитие ...,2026-06-30T16:52:15,https://news.itmo.ru/ru/education/official/new...

In [5]:
news_df.to_csv(
    GENERAL_CSV,
    index=False,
    encoding="utf-8"
)

print("Сохранено:", GENERAL_CSV.resolve())
print("Строк:", len(news_df))

Сохранено: /Users/infinitrator/infinitrator.github.io/lab8/news.csv
Строк: 1147

## 5. Парсинг страницы конкретной новости

Для каждой страницы новости собираются:

- идентификатор;
- название;
- дата публикации;
- количество просмотров;
- основной текст;
- теги.

На сайте встречается различная внутренняя разметка материалов, поэтому для текста используются несколько вариантов селекторов и резервный способ извлечения.

### Особенность исторических материалов

На части старых страниц ITMO.NEWS публичный счётчик просмотров отсутствует в HTML. Для таких публикаций поле `views` сохраняется как пропущенное значение (`NaN`), а не заменяется нулём, поскольку ноль означал бы известное количество просмотров и искажал данные.


### Вариативность HTML-разметки

В старых материалах сайта встречаются вложенные HTML-абзацы. Поэтому текст извлекается из контейнера статьи целиком, а не объединением результатов для каждого `<p>` по отдельности. Иначе содержимое вложенных элементов может несколько раз попадать в итоговый текст.

Некоторые интерактивные и медийные публикации не имеют обычного текстового тела в серверном HTML. Для таких материалов `text` сохраняется как пропущенное значение (`NaN`), а не заменяется служебными элементами страницы.

In [6]:
def extract_tags(soup):
    """Находит группу с подписью 'Теги'."""
    for group in soup.select("div.group"):
        label = group.select_one(".label")

        if label is None:
            continue

        if clean_text(label.get_text()) != "Теги":
            continue

        return [
            clean_text(link.get_text(" ", strip=True))
            for link in group.select("ul.tags a")
            if clean_text(link.get_text(" ", strip=True))
        ]

    return []


def extract_article_text(soup):
    """Извлекает основной текст с учётом вариантов верстки."""

    content = soup.select_one(
        ".article .content.js-mediator-article"
    )

    if content is None:
        content = soup.select_one(".article .post-content")

    if content is None:
        content = soup.select_one(".article")

    if content is None:
        return None

    # Удаляем служебные элементы внутри контейнера статьи.
    for tag in content.select(
        "script, style, .post-content__top-link"
    ):
        tag.decompose()

    # Текст извлекается из контейнера целиком.
    #
    # Это важно для старых материалов: в их HTML встречаются
    # вложенные теги <p>. Если извлекать каждый <p> отдельно,
    # текст дочерних элементов несколько раз попадёт в результат.
    text = clean_text(
        content.get_text(" ", strip=True)
    )

    if not text:
        return None

    # Некоторые интерактивные/медийные публикации не содержат
    # обычного текстового тела в серверном HTML.
    if text in {".", "К началу", ". К началу"}:
        return None

    return text


def parse_article(row):
    soup = get_soup(row["url"])

    title_tag = soup.select_one(".article h1") or soup.find("h1")

    title = (
        clean_text(title_tag.get_text(" ", strip=True))
        if title_tag
        else row["title"]
    )

    time_tag = soup.select_one(".news-info-wrapper time")

    date = (
        time_tag.get("datetime")
        if time_tag
        else row["date"]
    )

    views = None

    if time_tag is not None:
        views_tag = time_tag.select_one("span.icon.eye")

        if views_tag is not None:
            views_text = clean_text(
                views_tag.get_text(" ", strip=True)
            ) or ""

            digits = re.sub(r"\D", "", views_text)

            if digits:
                views = int(digits)

    text = extract_article_text(soup)
    tags = extract_tags(soup)

    return {
        "id": int(row["id"]),
        "title": title,
        "date": date,
        "views": views,
        "text": text,
        "tags": "; ".join(tags),
        "url": row["url"],
    }

## 6. Проверка парсера на одной новости

Перед массовым сбором проверяем, что все требуемые поля корректно извлекаются с одной страницы.

In [7]:
sample = parse_article(news_df.iloc[0])

print("ID:", sample["id"])
print("Название:", sample["title"])
print("Дата:", sample["date"])
print("Просмотры:", sample["views"])
print("Теги:", sample["tags"])
print()
print("Начало текста:")
print((sample["text"] or "")[:1000])

ID:

 15033
Название: Соединили пышки и квантовую механику: как ИТМО и Яндекс Образование провели научный мини-фестиваль в пяти городах России
Дата: 2026-09-21T18:24:25+03:00
Просмотры: 121
Теги: Главное; Геймификация; Фестивали; Яндекс Образование

Начало текста:
Более четырех тысяч километров, пять городов и 6400 горячих пышек: рассказываем, как прошла « Киберпышечная », большое путешествие ИТМО и Яндекс Образования про науку и профессии будущего. За две с половиной недели брендированный фудтрак посетил Москву, Нижний Новгород, Казань, Екатеринбург и Санкт-Петербург, став точкой притяжения для тех, кто любит думать и вкусно поесть. Подробнее — в материале ITMO NEWS. Научный мини-фестиваль «Киберпышечная». Фото: ИТМО и Яндекс Образование «Киберпышечная» — совместный проект ИТМО и Яндекс Образования, который объединил популярную науку, современные технологии и городскую культуру. Главным драйвером проекта, угощением для гостей и частью игровой механики стала петербургская пышка. Чтобы получить пышки, а заодно фирменный мерч и другие призы, участники зарабатывали пышкотокены — внутреннюю валюту «Киберпышечной». Их можно было добыть за участие в играх, лекциях и онлайн-активностях, а потом обменять на подарки, в том числе на главный приз — игровую

## 7. Сбор содержимого всех новостей

В тестовом режиме обрабатываются только первые 10 новостей. После проверки результатов ограничение будет снято.

In [8]:
ERRORS_CSV = OUTPUT_DIR / "errors.csv"
CHECKPOINT_EVERY = 25

if FULL_CONTENT:
    source_df = news_df.copy()

    # Если полный сбор был прерван, продолжаем с уже
    # сохраненного чекпоинта.
    if CONTENT_CSV.exists():
        existing_df = pd.read_csv(CONTENT_CSV)

        if not existing_df.empty and "id" in existing_df.columns:
            existing_df["id"] = existing_df["id"].astype(int)
        else:
            existing_df = pd.DataFrame()

    else:
        existing_df = pd.DataFrame()

    processed_ids = (
        set(existing_df["id"].tolist())
        if not existing_df.empty
        else set()
    )

    source_df = source_df[
        ~source_df["id"].isin(processed_ids)
    ].copy()

    content_df = existing_df.copy()

    print("Уже сохранено:", len(processed_ids))
    print("Осталось обработать:", len(source_df))

else:
    positions = sorted(set([
        0,
        len(news_df) // 2,
        len(news_df) - 1,
    ]))

    source_df = news_df.iloc[positions].copy()
    content_df = pd.DataFrame()

    print("Контрольные статьи:")
    display(source_df[["id", "title", "date", "url"]])


content_rows = []
errors = []


def save_checkpoint():
    global content_df, content_rows

    if content_rows:
        batch_df = pd.DataFrame(content_rows)

        content_df = pd.concat(
            [content_df, batch_df],
            ignore_index=True,
        )

        content_rows = []

    if not content_df.empty:
        content_df = (
            content_df
            .drop_duplicates(subset="id", keep="last")
            .sort_values("id", ascending=False)
            .reset_index(drop=True)
        )

        content_df.to_csv(
            CONTENT_CSV,
            index=False,
            encoding="utf-8",
        )

    if errors:
        pd.DataFrame(errors).to_csv(
            ERRORS_CSV,
            index=False,
            encoding="utf-8",
        )


for number, (_, row) in enumerate(
    tqdm(
        source_df.iterrows(),
        total=len(source_df),
        desc="Парсинг новостей",
    ),
    start=1,
):
    try:
        content_rows.append(parse_article(row))

    except Exception as error:
        errors.append({
            "id": int(row["id"]),
            "url": row["url"],
            "error": repr(error),
        })

    if number % CHECKPOINT_EVERY == 0:
        save_checkpoint()

    time.sleep(REQUEST_DELAY)


save_checkpoint()

print()
print("Всего сохранено статей:", len(content_df))
print("Ошибок этого запуска:", len(errors))

if errors:
    display(pd.DataFrame(errors))

content_df.head()

Уже сохранено: 0
Осталось обработать: 1147

Парсинг новостей:   0%|                    | 0/1147 [00:00<?, ?it/s]

Парсинг новостей:   0%|            | 1/1147 [00:00<09:26,  2.02it/s]

Парсинг новостей:   0%|            | 2/1147 [00:01<09:41,  1.97it/s]

Парсинг новостей:   0%|            | 3/1147 [00:01<09:46,  1.95it/s]

Парсинг новостей:   0%|            | 4/1147 [00:01<09:00,  2.11it/s]

Парсинг новостей:   0%|            | 5/1147 [00:02<08:28,  2.25it/s]

Парсинг новостей:   1%|            | 6/1147 [00:02<08:06,  2.34it/s]

Парсинг новостей:   1%|            | 7/1147 [00:03<08:14,  2.30it/s]

Парсинг новостей:   1%|            | 8/1147 [00:03<08:22,  2.27it/s]

Парсинг новостей:   1%|            | 9/1147 [00:04<08:04,  2.35it/s]

Парсинг новостей:   1%|           | 10/1147 [00:04<07:54,  2.40it/s]

Парсинг новостей:   1%|           | 11/1147 [00:04<08:03,  2.35it/s]

Парсинг новостей:   1%|           | 12/1147 [00:05<09:38,  1.96it/s]

Парсинг новостей:   1%|           | 13/1147 [00:05<09:09,  2.06it/s]

Парсинг новостей:   1%|▏          | 14/1147 [00:06<08:32,  2.21it/s]

Парсинг новостей:   1%|▏          | 15/1147 [00:06<08:42,  2.17it/s]

Парсинг новостей:   1%|▏          | 16/1147 [00:07<08:54,  2.12it/s]

Парсинг новостей:   1%|▏          | 17/1147 [00:07<09:03,  2.08it/s]

Парсинг новостей:   2%|▏          | 18/1147 [00:08<09:30,  1.98it/s]

Парсинг новостей:   2%|▏          | 19/1147 [00:08<09:32,  1.97it/s]

Парсинг новостей:   2%|▏          | 20/1147 [00:09<09:27,  1.99it/s]

Парсинг новостей:   2%|▏          | 21/1147 [00:09<08:49,  2.13it/s]

Парсинг новостей:   2%|▏          | 22/1147 [00:10<08:25,  2.23it/s]

Парсинг новостей:   2%|▏          | 23/1147 [00:11<10:22,  1.80it/s]

Парсинг новостей:   2%|▏          | 24/1147 [00:11<09:56,  1.88it/s]

Парсинг новостей:   2%|▏          | 25/1147 [00:11<09:13,  2.03it/s]

Парсинг новостей:   2%|▏          | 26/1147 [00:12<08:39,  2.16it/s]

Парсинг новостей:   2%|▎          | 27/1147 [00:12<08:11,  2.28it/s]

Парсинг новостей:   2%|▎          | 28/1147 [00:13<08:00,  2.33it/s]

Парсинг новостей:   3%|▎          | 29/1147 [00:13<07:46,  2.39it/s]

Парсинг новостей:   3%|▎          | 30/1147 [00:13<07:45,  2.40it/s]

Парсинг новостей:   3%|▎          | 31/1147 [00:14<07:34,  2.45it/s]

Парсинг новостей:   3%|▎          | 32/1147 [00:14<07:53,  2.35it/s]

Парсинг новостей:   3%|▎          | 33/1147 [00:15<08:02,  2.31it/s]

Парсинг новостей:   3%|▎          | 34/1147 [00:15<07:48,  2.38it/s]

Парсинг новостей:   3%|▎          | 35/1147 [00:15<07:44,  2.39it/s]

Парсинг новостей:   3%|▎          | 36/1147 [00:16<07:39,  2.42it/s]

Парсинг новостей:   3%|▎          | 37/1147 [00:16<07:53,  2.34it/s]

Парсинг новостей:   3%|▎          | 38/1147 [00:17<07:53,  2.34it/s]

Парсинг новостей:   3%|▎          | 39/1147 [00:17<07:43,  2.39it/s]

Парсинг новостей:   3%|▍          | 40/1147 [00:18<07:34,  2.43it/s]

Парсинг новостей:   4%|▍          | 41/1147 [00:18<07:36,  2.42it/s]

Парсинг новостей:   4%|▍          | 42/1147 [00:18<07:38,  2.41it/s]

Парсинг новостей:   4%|▍          | 43/1147 [00:19<07:49,  2.35it/s]

Парсинг новостей:   4%|▍          | 44/1147 [00:19<07:38,  2.40it/s]

Парсинг новостей:   4%|▍          | 45/1147 [00:20<07:28,  2.46it/s]

Парсинг новостей:   4%|▍          | 46/1147 [00:20<07:27,  2.46it/s]

Парсинг новостей:   4%|▍          | 47/1147 [00:20<07:40,  2.39it/s]

Парсинг новостей:   4%|▍          | 48/1147 [00:21<07:56,  2.31it/s]

Парсинг новостей:   4%|▍          | 49/1147 [00:21<08:25,  2.17it/s]

Парсинг новостей:   4%|▍          | 50/1147 [00:22<08:10,  2.23it/s]

Парсинг новостей:   4%|▍          | 51/1147 [00:22<07:58,  2.29it/s]

Парсинг новостей:   5%|▍          | 52/1147 [00:23<08:03,  2.27it/s]

Парсинг новостей:   5%|▌          | 53/1147 [00:23<07:50,  2.32it/s]

Парсинг новостей:   5%|▌          | 54/1147 [00:24<08:05,  2.25it/s]

Парсинг новостей:   5%|▌          | 55/1147 [00:24<09:51,  1.84it/s]

Парсинг новостей:   5%|▌          | 56/1147 [00:25<10:24,  1.75it/s]

Парсинг новостей:   5%|▌          | 57/1147 [00:25<09:21,  1.94it/s]

Парсинг новостей:   5%|▌          | 58/1147 [00:26<08:45,  2.07it/s]

Парсинг новостей:   5%|▌          | 59/1147 [00:26<08:40,  2.09it/s]

Парсинг новостей:   5%|▌          | 60/1147 [00:27<08:23,  2.16it/s]

Парсинг новостей:   5%|▌          | 61/1147 [00:27<07:53,  2.29it/s]

Парсинг новостей:   5%|▌          | 62/1147 [00:28<07:43,  2.34it/s]

Парсинг новостей:   5%|▌          | 63/1147 [00:28<07:30,  2.41it/s]

Парсинг новостей:   6%|▌          | 64/1147 [00:28<07:35,  2.38it/s]

Парсинг новостей:   6%|▌          | 65/1147 [00:29<07:53,  2.28it/s]

Парсинг новостей:   6%|▋          | 66/1147 [00:29<07:42,  2.34it/s]

Парсинг новостей:   6%|▋          | 67/1147 [00:30<07:26,  2.42it/s]

Парсинг новостей:   6%|▋          | 68/1147 [00:30<07:18,  2.46it/s]

Парсинг новостей:   6%|▋          | 69/1147 [00:30<07:19,  2.45it/s]

Парсинг новостей:   6%|▋          | 70/1147 [00:31<07:10,  2.50it/s]

Парсинг новостей:   6%|▋          | 71/1147 [00:31<06:57,  2.58it/s]

Парсинг новостей:   6%|▋          | 72/1147 [00:32<07:02,  2.55it/s]

Парсинг новостей:   6%|▋          | 73/1147 [00:32<07:17,  2.46it/s]

Парсинг новостей:   6%|▋          | 74/1147 [00:32<07:07,  2.51it/s]

Парсинг новостей:   7%|▋          | 75/1147 [00:33<08:36,  2.07it/s]

Парсинг новостей:   7%|▋          | 76/1147 [00:34<08:38,  2.06it/s]

Парсинг новостей:   7%|▋          | 77/1147 [00:34<08:09,  2.19it/s]

Парсинг новостей:   7%|▋          | 78/1147 [00:34<07:38,  2.33it/s]

Парсинг новостей:   7%|▊          | 79/1147 [00:35<07:32,  2.36it/s]

Парсинг новостей:   7%|▊          | 80/1147 [00:35<07:37,  2.33it/s]

Парсинг новостей:   7%|▊          | 81/1147 [00:36<07:24,  2.40it/s]

Парсинг новостей:   7%|▊          | 82/1147 [00:36<07:11,  2.47it/s]

Парсинг новостей:   7%|▊          | 83/1147 [00:36<07:07,  2.49it/s]

Парсинг новостей:   7%|▊          | 84/1147 [00:37<07:11,  2.46it/s]

Парсинг новостей:   7%|▊          | 85/1147 [00:37<07:15,  2.44it/s]

Парсинг новостей:   7%|▊          | 86/1147 [00:38<07:12,  2.45it/s]

Парсинг новостей:   8%|▊          | 87/1147 [00:38<07:04,  2.50it/s]

Парсинг новостей:   8%|▊          | 88/1147 [00:38<07:31,  2.35it/s]

Парсинг новостей:   8%|▊          | 89/1147 [00:39<07:42,  2.29it/s]

Парсинг новостей:   8%|▊          | 90/1147 [00:39<07:57,  2.21it/s]

Парсинг новостей:   8%|▊          | 91/1147 [00:40<08:04,  2.18it/s]

Парсинг новостей:   8%|▉          | 92/1147 [00:40<07:45,  2.27it/s]

Парсинг новостей:   8%|▉          | 93/1147 [00:41<07:28,  2.35it/s]

Парсинг новостей:   8%|▉          | 94/1147 [00:41<07:08,  2.46it/s]

Парсинг новостей:   8%|▉          | 95/1147 [00:41<07:23,  2.37it/s]

Парсинг новостей:   8%|▉          | 96/1147 [00:42<07:47,  2.25it/s]

Парсинг новостей:   8%|▉          | 97/1147 [00:42<07:29,  2.34it/s]

Парсинг новостей:   9%|▉          | 98/1147 [00:43<07:18,  2.39it/s]

Парсинг новостей:   9%|▉          | 99/1147 [00:43<07:00,  2.49it/s]

Парсинг новостей:   9%|▊         | 100/1147 [00:44<07:24,  2.36it/s]

Парсинг новостей:   9%|▉         | 101/1147 [00:44<07:38,  2.28it/s]

Парсинг новостей:   9%|▉         | 102/1147 [00:44<07:29,  2.32it/s]

Парсинг новостей:   9%|▉         | 103/1147 [00:45<07:08,  2.44it/s]

Парсинг новостей:   9%|▉         | 104/1147 [00:45<08:13,  2.12it/s]

Парсинг новостей:   9%|▉         | 105/1147 [00:46<07:50,  2.22it/s]

Парсинг новостей:   9%|▉         | 106/1147 [00:46<07:32,  2.30it/s]

Парсинг новостей:   9%|▉         | 107/1147 [00:47<07:42,  2.25it/s]

Парсинг новостей:   9%|▉         | 108/1147 [00:47<07:51,  2.21it/s]

Парсинг новостей:  10%|▉         | 109/1147 [00:48<07:37,  2.27it/s]

Парсинг новостей:  10%|▉         | 110/1147 [00:48<07:17,  2.37it/s]

Парсинг новостей:  10%|▉         | 111/1147 [00:48<07:05,  2.44it/s]

Парсинг новостей:  10%|▉         | 112/1147 [00:49<07:14,  2.38it/s]

Парсинг новостей:  10%|▉         | 113/1147 [00:49<07:02,  2.44it/s]

Парсинг новостей:  10%|▉         | 114/1147 [00:50<06:50,  2.52it/s]

Парсинг новостей:  10%|█         | 115/1147 [00:50<06:42,  2.56it/s]

Парсинг новостей:  10%|█         | 116/1147 [00:50<06:52,  2.50it/s]

Парсинг новостей:  10%|█         | 117/1147 [00:51<06:41,  2.57it/s]

Парсинг новостей:  10%|█         | 118/1147 [00:51<06:34,  2.61it/s]

Парсинг новостей:  10%|█         | 119/1147 [00:51<06:39,  2.57it/s]

Парсинг новостей:  10%|█         | 120/1147 [00:52<07:03,  2.42it/s]

Парсинг новостей:  11%|█         | 121/1147 [00:52<06:47,  2.52it/s]

Парсинг новостей:  11%|█         | 122/1147 [00:53<06:47,  2.52it/s]

Парсинг новостей:  11%|█         | 123/1147 [00:53<06:34,  2.60it/s]

Парсинг новостей:  11%|█         | 124/1147 [00:53<06:46,  2.51it/s]

Парсинг новостей:  11%|█         | 125/1147 [00:54<06:50,  2.49it/s]

Парсинг новостей:  11%|█         | 126/1147 [00:54<06:51,  2.48it/s]

Парсинг новостей:  11%|█         | 127/1147 [00:55<06:53,  2.47it/s]

Парсинг новостей:  11%|█         | 128/1147 [00:55<08:19,  2.04it/s]

Парсинг новостей:  11%|█         | 129/1147 [00:56<08:19,  2.04it/s]

Парсинг новостей:  11%|█▏        | 130/1147 [00:56<07:57,  2.13it/s]

Парсинг новостей:  11%|█▏        | 131/1147 [00:57<09:00,  1.88it/s]

Парсинг новостей:  12%|█▏        | 132/1147 [00:57<08:19,  2.03it/s]

Парсинг новостей:  12%|█▏        | 133/1147 [00:58<07:57,  2.12it/s]

Парсинг новостей:  12%|█▏        | 134/1147 [00:58<08:25,  2.00it/s]

Парсинг новостей:  12%|█▏        | 135/1147 [00:59<08:13,  2.05it/s]

Парсинг новостей:  12%|█▏        | 136/1147 [00:59<07:56,  2.12it/s]

Парсинг новостей:  12%|█▏        | 137/1147 [01:00<07:30,  2.24it/s]

Парсинг новостей:  12%|█▏        | 138/1147 [01:00<07:11,  2.34it/s]

Парсинг новостей:  12%|█▏        | 139/1147 [01:01<09:11,  1.83it/s]

Парсинг новостей:  12%|█▏        | 140/1147 [01:01<08:49,  1.90it/s]

Парсинг новостей:  12%|█▏        | 141/1147 [01:02<07:58,  2.10it/s]

Парсинг новостей:  12%|█▏        | 142/1147 [01:02<07:34,  2.21it/s]

Парсинг новостей:  12%|█▏        | 143/1147 [01:03<07:27,  2.24it/s]

Парсинг новостей:  13%|█▎        | 144/1147 [01:03<07:45,  2.16it/s]

Парсинг новостей:  13%|█▎        | 145/1147 [01:04<08:46,  1.90it/s]

Парсинг новостей:  13%|█▎        | 146/1147 [01:04<09:23,  1.78it/s]

Парсинг новостей:  13%|█▎        | 147/1147 [01:05<08:23,  1.99it/s]

Парсинг новостей:  13%|█▎        | 148/1147 [01:05<07:47,  2.14it/s]

Парсинг новостей:  13%|█▎        | 149/1147 [01:06<07:47,  2.13it/s]

Парсинг новостей:  13%|█▎        | 150/1147 [01:06<07:21,  2.26it/s]

Парсинг новостей:  13%|█▎        | 151/1147 [01:06<07:04,  2.35it/s]

Парсинг новостей:  13%|█▎        | 152/1147 [01:07<06:52,  2.41it/s]

Парсинг новостей:  13%|█▎        | 153/1147 [01:07<07:11,  2.31it/s]

Парсинг новостей:  13%|█▎        | 154/1147 [01:08<07:15,  2.28it/s]

Парсинг новостей:  14%|█▎        | 155/1147 [01:08<07:42,  2.15it/s]

Парсинг новостей:  14%|█▎        | 156/1147 [01:09<07:50,  2.10it/s]

Парсинг новостей:  14%|█▎        | 157/1147 [01:09<07:25,  2.22it/s]

Парсинг новостей:  14%|█▍        | 158/1147 [01:09<07:13,  2.28it/s]

Парсинг новостей:  14%|█▍        | 159/1147 [01:10<07:12,  2.28it/s]

Парсинг новостей:  14%|█▍        | 160/1147 [01:10<07:06,  2.32it/s]

Парсинг новостей:  14%|█▍        | 161/1147 [01:11<07:24,  2.22it/s]

Парсинг новостей:  14%|█▍        | 162/1147 [01:11<07:28,  2.20it/s]

Парсинг новостей:  14%|█▍        | 163/1147 [01:12<07:02,  2.33it/s]

Парсинг новостей:  14%|█▍        | 164/1147 [01:12<06:43,  2.44it/s]

Парсинг новостей:  14%|█▍        | 165/1147 [01:12<06:33,  2.50it/s]

Парсинг новостей:  14%|█▍        | 166/1147 [01:13<06:47,  2.40it/s]

Парсинг новостей:  15%|█▍        | 167/1147 [01:13<06:36,  2.47it/s]

Парсинг новостей:  15%|█▍        | 168/1147 [01:14<06:26,  2.53it/s]

Парсинг новостей:  15%|█▍        | 169/1147 [01:14<06:24,  2.54it/s]

Парсинг новостей:  15%|█▍        | 170/1147 [01:14<06:44,  2.42it/s]

Парсинг новостей:  15%|█▍        | 171/1147 [01:15<06:32,  2.49it/s]

Парсинг новостей:  15%|█▍        | 172/1147 [01:15<06:19,  2.57it/s]

Парсинг новостей:  15%|█▌        | 173/1147 [01:16<06:17,  2.58it/s]

Парсинг новостей:  15%|█▌        | 174/1147 [01:16<06:40,  2.43it/s]

Парсинг новостей:  15%|█▌        | 175/1147 [01:16<06:33,  2.47it/s]

Парсинг новостей:  15%|█▌        | 176/1147 [01:17<06:22,  2.54it/s]

Парсинг новостей:  15%|█▌        | 177/1147 [01:17<06:15,  2.58it/s]

Парсинг новостей:  16%|█▌        | 178/1147 [01:18<06:20,  2.55it/s]

Парсинг новостей:  16%|█▌        | 179/1147 [01:18<06:21,  2.54it/s]

Парсинг новостей:  16%|█▌        | 180/1147 [01:18<06:18,  2.56it/s]

Парсинг новостей:  16%|█▌        | 181/1147 [01:19<06:15,  2.57it/s]

Парсинг новостей:  16%|█▌        | 182/1147 [01:19<06:23,  2.51it/s]

Парсинг новостей:  16%|█▌        | 183/1147 [01:20<06:22,  2.52it/s]

Парсинг новостей:  16%|█▌        | 184/1147 [01:20<07:30,  2.14it/s]

Парсинг новостей:  16%|█▌        | 185/1147 [01:21<07:12,  2.23it/s]

Парсинг новостей:  16%|█▌        | 186/1147 [01:21<06:57,  2.30it/s]

Парсинг новостей:  16%|█▋        | 187/1147 [01:21<06:48,  2.35it/s]

Парсинг новостей:  16%|█▋        | 188/1147 [01:22<08:19,  1.92it/s]

Парсинг новостей:  16%|█▋        | 189/1147 [01:23<07:37,  2.10it/s]

Парсинг новостей:  17%|█▋        | 190/1147 [01:23<07:16,  2.19it/s]

Парсинг новостей:  17%|█▋        | 191/1147 [01:23<07:16,  2.19it/s]

Парсинг новостей:  17%|█▋        | 192/1147 [01:24<06:49,  2.33it/s]

Парсинг новостей:  17%|█▋        | 193/1147 [01:24<06:32,  2.43it/s]

Парсинг новостей:  17%|█▋        | 194/1147 [01:25<06:37,  2.40it/s]

Парсинг новостей:  17%|█▋        | 195/1147 [01:25<06:47,  2.34it/s]

Парсинг новостей:  17%|█▋        | 196/1147 [01:25<07:00,  2.26it/s]

Парсинг новостей:  17%|█▋        | 197/1147 [01:26<06:40,  2.37it/s]

Парсинг новостей:  17%|█▋        | 198/1147 [01:26<06:30,  2.43it/s]

Парсинг новостей:  17%|█▋        | 199/1147 [01:27<06:16,  2.52it/s]

Парсинг новостей:  17%|█▋        | 200/1147 [01:27<06:40,  2.37it/s]

Парсинг новостей:  18%|█▊        | 201/1147 [01:28<06:46,  2.33it/s]

Парсинг новостей:  18%|█▊        | 202/1147 [01:28<06:31,  2.42it/s]

Парсинг новостей:  18%|█▊        | 203/1147 [01:28<06:12,  2.54it/s]

Парсинг новостей:  18%|█▊        | 204/1147 [01:29<06:22,  2.47it/s]

Парсинг новостей:  18%|█▊        | 205/1147 [01:29<06:30,  2.41it/s]

Парсинг новостей:  18%|█▊        | 206/1147 [01:30<06:22,  2.46it/s]

Парсинг новостей:  18%|█▊        | 207/1147 [01:30<06:29,  2.42it/s]

Парсинг новостей:  18%|█▊        | 208/1147 [01:30<06:29,  2.41it/s]

Парсинг новостей:  18%|█▊        | 209/1147 [01:31<06:47,  2.30it/s]

Парсинг новостей:  18%|█▊        | 210/1147 [01:31<07:06,  2.20it/s]

Парсинг новостей:  18%|█▊        | 211/1147 [01:32<07:01,  2.22it/s]

Парсинг новостей:  18%|█▊        | 212/1147 [01:32<07:17,  2.14it/s]

Парсинг новостей:  19%|█▊        | 213/1147 [01:33<06:56,  2.24it/s]

Парсинг новостей:  19%|█▊        | 214/1147 [01:33<06:44,  2.30it/s]

Парсинг новостей:  19%|█▊        | 215/1147 [01:33<06:30,  2.39it/s]

Парсинг новостей:  19%|█▉        | 216/1147 [01:34<06:42,  2.31it/s]

Парсинг новостей:  19%|█▉        | 217/1147 [01:34<06:53,  2.25it/s]

Парсинг новостей:  19%|█▉        | 218/1147 [01:35<07:38,  2.03it/s]

Парсинг новостей:  19%|█▉        | 219/1147 [01:36<07:36,  2.03it/s]

Парсинг новостей:  19%|█▉        | 220/1147 [01:36<07:26,  2.07it/s]

Парсинг новостей:  19%|█▉        | 221/1147 [01:36<07:34,  2.04it/s]

Парсинг новостей:  19%|█▉        | 222/1147 [01:37<07:34,  2.04it/s]

Парсинг новостей:  19%|█▉        | 223/1147 [01:37<07:06,  2.16it/s]

Парсинг новостей:  20%|█▉        | 224/1147 [01:38<06:45,  2.28it/s]

Парсинг новостей:  20%|█▉        | 225/1147 [01:38<06:30,  2.36it/s]

Парсинг новостей:  20%|█▉        | 226/1147 [01:39<06:31,  2.35it/s]

Парсинг новостей:  20%|█▉        | 227/1147 [01:39<06:50,  2.24it/s]

Парсинг новостей:  20%|█▉        | 228/1147 [01:39<06:43,  2.28it/s]

Парсинг новостей:  20%|█▉        | 229/1147 [01:40<06:35,  2.32it/s]

Парсинг новостей:  20%|██        | 230/1147 [01:40<06:26,  2.37it/s]

Парсинг новостей:  20%|██        | 231/1147 [01:41<06:35,  2.31it/s]

Парсинг новостей:  20%|██        | 232/1147 [01:41<06:40,  2.29it/s]

Парсинг новостей:  20%|██        | 233/1147 [01:42<06:23,  2.38it/s]

Парсинг новостей:  20%|██        | 234/1147 [01:42<06:13,  2.44it/s]

Парсинг новостей:  20%|██        | 235/1147 [01:42<06:08,  2.48it/s]

Парсинг новостей:  21%|██        | 236/1147 [01:43<06:09,  2.47it/s]

Парсинг новостей:  21%|██        | 237/1147 [01:43<06:07,  2.48it/s]

Парсинг новостей:  21%|██        | 238/1147 [01:44<06:10,  2.45it/s]

Парсинг новостей:  21%|██        | 239/1147 [01:44<06:11,  2.44it/s]

Парсинг новостей:  21%|██        | 240/1147 [01:44<06:21,  2.38it/s]

Парсинг новостей:  21%|██        | 241/1147 [01:45<07:34,  1.99it/s]

Парсинг новостей:  21%|██        | 242/1147 [01:46<07:02,  2.14it/s]

Парсинг новостей:  21%|██        | 243/1147 [01:46<07:09,  2.10it/s]

Парсинг новостей:  21%|██▏       | 244/1147 [01:46<07:01,  2.14it/s]

Парсинг новостей:  21%|██▏       | 245/1147 [01:47<07:01,  2.14it/s]

Парсинг новостей:  21%|██▏       | 246/1147 [01:47<07:18,  2.06it/s]

Парсинг новостей:  22%|██▏       | 247/1147 [01:48<08:02,  1.87it/s]

Парсинг новостей:  22%|██▏       | 248/1147 [01:49<07:35,  1.97it/s]

Парсинг новостей:  22%|██▏       | 249/1147 [01:49<07:00,  2.13it/s]

Парсинг новостей:  22%|██▏       | 250/1147 [01:49<06:47,  2.20it/s]

Парсинг новостей:  22%|██▏       | 251/1147 [01:50<06:43,  2.22it/s]

Парсинг новостей:  22%|██▏       | 252/1147 [01:50<06:44,  2.21it/s]

Парсинг новостей:  22%|██▏       | 253/1147 [01:51<06:40,  2.23it/s]

Парсинг новостей:  22%|██▏       | 254/1147 [01:51<06:38,  2.24it/s]

Парсинг новостей:  22%|██▏       | 255/1147 [01:52<06:29,  2.29it/s]

Парсинг новостей:  22%|██▏       | 256/1147 [01:52<06:20,  2.34it/s]

Парсинг новостей:  22%|██▏       | 257/1147 [01:52<06:02,  2.46it/s]

Парсинг новостей:  22%|██▏       | 258/1147 [01:53<06:26,  2.30it/s]

Парсинг новостей:  23%|██▎       | 259/1147 [01:54<07:39,  1.93it/s]

Парсинг новостей:  23%|██▎       | 260/1147 [01:54<07:23,  2.00it/s]

Парсинг новостей:  23%|██▎       | 261/1147 [01:54<06:58,  2.12it/s]

Парсинг новостей:  23%|██▎       | 262/1147 [01:55<07:06,  2.07it/s]

Парсинг новостей:  23%|██▎       | 263/1147 [01:55<07:06,  2.07it/s]

Парсинг новостей:  23%|██▎       | 264/1147 [01:56<07:12,  2.04it/s]

Парсинг новостей:  23%|██▎       | 265/1147 [01:56<06:42,  2.19it/s]

Парсинг новостей:  23%|██▎       | 266/1147 [01:57<07:27,  1.97it/s]

Парсинг новостей:  23%|██▎       | 267/1147 [01:57<06:56,  2.11it/s]

Парсинг новостей:  23%|██▎       | 268/1147 [01:58<06:43,  2.18it/s]

Парсинг новостей:  23%|██▎       | 269/1147 [01:58<06:29,  2.26it/s]

Парсинг новостей:  24%|██▎       | 270/1147 [01:59<06:43,  2.17it/s]

Парсинг новостей:  24%|██▎       | 271/1147 [01:59<06:51,  2.13it/s]

Парсинг новостей:  24%|██▎       | 272/1147 [02:00<06:59,  2.08it/s]

Парсинг новостей:  24%|██▍       | 273/1147 [02:00<07:10,  2.03it/s]

Парсинг новостей:  24%|██▍       | 274/1147 [02:01<07:07,  2.04it/s]

Парсинг новостей:  24%|██▍       | 275/1147 [02:01<07:18,  1.99it/s]

Парсинг новостей:  24%|██▍       | 276/1147 [02:02<07:06,  2.04it/s]

Парсинг новостей:  24%|██▍       | 277/1147 [02:02<06:41,  2.17it/s]

Парсинг новостей:  24%|██▍       | 278/1147 [02:02<06:20,  2.28it/s]

Парсинг новостей:  24%|██▍       | 279/1147 [02:03<06:08,  2.35it/s]

Парсинг новостей:  24%|██▍       | 280/1147 [02:03<06:13,  2.32it/s]

Парсинг новостей:  24%|██▍       | 281/1147 [02:04<06:00,  2.41it/s]

Парсинг новостей:  25%|██▍       | 282/1147 [02:04<05:49,  2.48it/s]

Парсинг новостей:  25%|██▍       | 283/1147 [02:04<05:37,  2.56it/s]

Парсинг новостей:  25%|██▍       | 284/1147 [02:05<08:09,  1.76it/s]

Парсинг новостей:  25%|██▍       | 285/1147 [02:06<07:52,  1.82it/s]

Парсинг новостей:  25%|██▍       | 286/1147 [02:06<07:12,  1.99it/s]

Парсинг новостей:  25%|██▌       | 287/1147 [02:07<07:49,  1.83it/s]

Парсинг новостей:  25%|██▌       | 288/1147 [02:07<07:08,  2.00it/s]

Парсинг новостей:  25%|██▌       | 289/1147 [02:08<06:38,  2.15it/s]

Парсинг новостей:  25%|██▌       | 290/1147 [02:08<06:23,  2.24it/s]

Парсинг новостей:  25%|██▌       | 291/1147 [02:08<06:13,  2.29it/s]

Парсинг новостей:  25%|██▌       | 292/1147 [02:09<06:27,  2.21it/s]

Парсинг новостей:  26%|██▌       | 293/1147 [02:09<06:15,  2.28it/s]

Парсинг новостей:  26%|██▌       | 294/1147 [02:10<06:04,  2.34it/s]

Парсинг новостей:  26%|██▌       | 295/1147 [02:10<06:02,  2.35it/s]

Парсинг новостей:  26%|██▌       | 296/1147 [02:11<06:09,  2.30it/s]

Парсинг новостей:  26%|██▌       | 297/1147 [02:11<06:13,  2.28it/s]

Парсинг новостей:  26%|██▌       | 298/1147 [02:11<06:01,  2.35it/s]

Парсинг новостей:  26%|██▌       | 299/1147 [02:12<05:44,  2.46it/s]

Парсинг новостей:  26%|██▌       | 300/1147 [02:12<05:49,  2.42it/s]

Парсинг новостей:  26%|██▌       | 301/1147 [02:13<05:56,  2.37it/s]

Парсинг новостей:  26%|██▋       | 302/1147 [02:13<06:08,  2.29it/s]

Парсинг новостей:  26%|██▋       | 303/1147 [02:14<06:20,  2.22it/s]

Парсинг новостей:  27%|██▋       | 304/1147 [02:14<06:08,  2.29it/s]

Парсинг новостей:  27%|██▋       | 305/1147 [02:15<06:03,  2.32it/s]

Парсинг новостей:  27%|██▋       | 306/1147 [02:15<06:02,  2.32it/s]

Парсинг новостей:  27%|██▋       | 307/1147 [02:15<06:32,  2.14it/s]

Парсинг новостей:  27%|██▋       | 308/1147 [02:16<06:17,  2.22it/s]

Парсинг новостей:  27%|██▋       | 309/1147 [02:16<06:18,  2.21it/s]

Парсинг новостей:  27%|██▋       | 310/1147 [02:17<06:25,  2.17it/s]

Парсинг новостей:  27%|██▋       | 311/1147 [02:17<06:14,  2.23it/s]

Парсинг новостей:  27%|██▋       | 312/1147 [02:18<06:23,  2.18it/s]

Парсинг новостей:  27%|██▋       | 313/1147 [02:18<06:23,  2.17it/s]

Парсинг новостей:  27%|██▋       | 314/1147 [02:19<06:09,  2.25it/s]

Парсинг новостей:  27%|██▋       | 315/1147 [02:19<06:03,  2.29it/s]

Парсинг новостей:  28%|██▊       | 316/1147 [02:20<06:18,  2.20it/s]

Парсинг новостей:  28%|██▊       | 317/1147 [02:20<06:31,  2.12it/s]

Парсинг новостей:  28%|██▊       | 318/1147 [02:21<06:34,  2.10it/s]

Парсинг новостей:  28%|██▊       | 319/1147 [02:21<06:17,  2.19it/s]

Парсинг новостей:  28%|██▊       | 320/1147 [02:21<06:04,  2.27it/s]

Парсинг новостей:  28%|██▊       | 321/1147 [02:22<05:43,  2.41it/s]

Парсинг новостей:  28%|██▊       | 322/1147 [02:22<05:39,  2.43it/s]

Парсинг новостей:  28%|██▊       | 323/1147 [02:22<05:21,  2.56it/s]

Парсинг новостей:  28%|██▊       | 324/1147 [02:23<05:16,  2.60it/s]

Парсинг новостей:  28%|██▊       | 325/1147 [02:23<05:26,  2.52it/s]

Парсинг новостей:  28%|██▊       | 326/1147 [02:24<05:39,  2.42it/s]

Парсинг новостей:  29%|██▊       | 327/1147 [02:24<05:30,  2.48it/s]

Парсинг новостей:  29%|██▊       | 328/1147 [02:24<05:30,  2.48it/s]

Парсинг новостей:  29%|██▊       | 329/1147 [02:25<05:28,  2.49it/s]

Парсинг новостей:  29%|██▉       | 330/1147 [02:25<05:39,  2.41it/s]

Парсинг новостей:  29%|██▉       | 331/1147 [02:26<07:02,  1.93it/s]

Парсинг новостей:  29%|██▉       | 332/1147 [02:26<06:38,  2.05it/s]

Парсинг новостей:  29%|██▉       | 333/1147 [02:27<06:13,  2.18it/s]

Парсинг новостей:  29%|██▉       | 334/1147 [02:27<06:07,  2.21it/s]

Парсинг новостей:  29%|██▉       | 335/1147 [02:28<05:50,  2.32it/s]

Парсинг новостей:  29%|██▉       | 336/1147 [02:28<05:49,  2.32it/s]

Парсинг новостей:  29%|██▉       | 337/1147 [02:29<05:45,  2.34it/s]

Парсинг новостей:  29%|██▉       | 338/1147 [02:29<06:00,  2.24it/s]

Парсинг новостей:  30%|██▉       | 339/1147 [02:29<05:48,  2.32it/s]

Парсинг новостей:  30%|██▉       | 340/1147 [02:30<05:38,  2.38it/s]

Парсинг новостей:  30%|██▉       | 341/1147 [02:30<05:30,  2.44it/s]

Парсинг новостей:  30%|██▉       | 342/1147 [02:31<06:19,  2.12it/s]

Парсинг новостей:  30%|██▉       | 343/1147 [02:31<05:59,  2.24it/s]

Парсинг новостей:  30%|██▉       | 344/1147 [02:32<05:46,  2.32it/s]

Парсинг новостей:  30%|███       | 345/1147 [02:32<05:52,  2.27it/s]

Парсинг новостей:  30%|███       | 346/1147 [02:32<05:34,  2.40it/s]

Парсинг новостей:  30%|███       | 347/1147 [02:33<05:25,  2.46it/s]

Парсинг новостей:  30%|███       | 348/1147 [02:33<05:18,  2.51it/s]

Парсинг новостей:  30%|███       | 349/1147 [02:34<05:34,  2.38it/s]

Парсинг новостей:  31%|███       | 350/1147 [02:34<05:52,  2.26it/s]

Парсинг новостей:  31%|███       | 351/1147 [02:35<05:38,  2.35it/s]

Парсинг новостей:  31%|███       | 352/1147 [02:35<05:27,  2.43it/s]

Парсинг новостей:  31%|███       | 353/1147 [02:35<05:13,  2.53it/s]

Парсинг новостей:  31%|███       | 354/1147 [02:36<05:28,  2.42it/s]

Парсинг новостей:  31%|███       | 355/1147 [02:36<05:22,  2.46it/s]

Парсинг новостей:  31%|███       | 356/1147 [02:37<05:18,  2.49it/s]

Парсинг новостей:  31%|███       | 357/1147 [02:37<05:07,  2.57it/s]

Парсинг новостей:  31%|███       | 358/1147 [02:37<05:16,  2.49it/s]

Парсинг новостей:  31%|███▏      | 359/1147 [02:38<05:08,  2.55it/s]

Парсинг новостей:  31%|███▏      | 360/1147 [02:38<05:07,  2.56it/s]

Парсинг новостей:  31%|███▏      | 361/1147 [02:38<05:11,  2.53it/s]

Парсинг новостей:  32%|███▏      | 362/1147 [02:39<05:42,  2.29it/s]

Парсинг новостей:  32%|███▏      | 363/1147 [02:39<05:52,  2.22it/s]

Парсинг новостей:  32%|███▏      | 364/1147 [02:40<05:51,  2.23it/s]

Парсинг новостей:  32%|███▏      | 365/1147 [02:40<05:36,  2.33it/s]

Парсинг новостей:  32%|███▏      | 366/1147 [02:41<05:25,  2.40it/s]

Парсинг новостей:  32%|███▏      | 367/1147 [02:41<05:18,  2.45it/s]

Парсинг новостей:  32%|███▏      | 368/1147 [02:42<05:21,  2.42it/s]

Парсинг новостей:  32%|███▏      | 369/1147 [02:42<05:35,  2.32it/s]

Парсинг новостей:  32%|███▏      | 370/1147 [02:42<05:31,  2.35it/s]

Парсинг новостей:  32%|███▏      | 371/1147 [02:43<05:25,  2.39it/s]

Парсинг новостей:  32%|███▏      | 372/1147 [02:43<05:11,  2.49it/s]

Парсинг новостей:  33%|███▎      | 373/1147 [02:44<05:14,  2.46it/s]

Парсинг новостей:  33%|███▎      | 374/1147 [02:44<05:09,  2.49it/s]

Парсинг новостей:  33%|███▎      | 375/1147 [02:45<06:20,  2.03it/s]

Парсинг новостей:  33%|███▎      | 376/1147 [02:45<06:10,  2.08it/s]

Парсинг новостей:  33%|███▎      | 377/1147 [02:46<06:41,  1.92it/s]

Парсинг новостей:  33%|███▎      | 378/1147 [02:46<06:40,  1.92it/s]

Парсинг новостей:  33%|███▎      | 379/1147 [02:47<06:36,  1.94it/s]

Парсинг новостей:  33%|███▎      | 380/1147 [02:47<06:28,  1.97it/s]

Парсинг новостей:  33%|███▎      | 381/1147 [02:48<06:26,  1.98it/s]

Парсинг новостей:  33%|███▎      | 382/1147 [02:48<05:57,  2.14it/s]

Парсинг новостей:  33%|███▎      | 383/1147 [02:49<05:52,  2.17it/s]

Парсинг новостей:  33%|███▎      | 384/1147 [02:49<05:36,  2.26it/s]

Парсинг новостей:  34%|███▎      | 385/1147 [02:49<05:38,  2.25it/s]

Парсинг новостей:  34%|███▎      | 386/1147 [02:50<05:37,  2.25it/s]

Парсинг новостей:  34%|███▎      | 387/1147 [02:50<05:24,  2.35it/s]

Парсинг новостей:  34%|███▍      | 388/1147 [02:51<05:18,  2.39it/s]

Парсинг новостей:  34%|███▍      | 389/1147 [02:51<05:19,  2.37it/s]

Парсинг новостей:  34%|███▍      | 390/1147 [02:52<05:40,  2.22it/s]

Парсинг новостей:  34%|███▍      | 391/1147 [02:52<05:47,  2.18it/s]

Парсинг новостей:  34%|███▍      | 392/1147 [02:53<05:39,  2.22it/s]

Парсинг новостей:  34%|███▍      | 393/1147 [02:53<05:20,  2.35it/s]

Парсинг новостей:  34%|███▍      | 394/1147 [02:53<05:08,  2.44it/s]

Парсинг новостей:  34%|███▍      | 395/1147 [02:54<05:01,  2.49it/s]

Парсинг новостей:  35%|███▍      | 396/1147 [02:54<06:09,  2.03it/s]

Парсинг новостей:  35%|███▍      | 397/1147 [02:55<05:47,  2.16it/s]

Парсинг новостей:  35%|███▍      | 398/1147 [02:55<05:48,  2.15it/s]

Парсинг новостей:  35%|███▍      | 399/1147 [02:56<05:48,  2.15it/s]

Парсинг новостей:  35%|███▍      | 400/1147 [02:56<05:57,  2.09it/s]

Парсинг новостей:  35%|███▍      | 401/1147 [02:57<06:01,  2.07it/s]

Парсинг новостей:  35%|███▌      | 402/1147 [02:57<05:49,  2.13it/s]

Парсинг новостей:  35%|███▌      | 403/1147 [02:58<05:34,  2.22it/s]

Парсинг новостей:  35%|███▌      | 404/1147 [02:58<05:21,  2.31it/s]

Парсинг новостей:  35%|███▌      | 405/1147 [02:58<05:15,  2.35it/s]

Парсинг новостей:  35%|███▌      | 406/1147 [02:59<05:20,  2.31it/s]

Парсинг новостей:  35%|███▌      | 407/1147 [02:59<05:04,  2.43it/s]

Парсинг новостей:  36%|███▌      | 408/1147 [03:00<06:05,  2.02it/s]

Парсинг новостей:  36%|███▌      | 409/1147 [03:00<05:42,  2.16it/s]

Парсинг новостей:  36%|███▌      | 410/1147 [03:01<06:22,  1.93it/s]

Парсинг новостей:  36%|███▌      | 411/1147 [03:01<05:51,  2.09it/s]

Парсинг новостей:  36%|███▌      | 412/1147 [03:02<05:28,  2.24it/s]

Парсинг новостей:  36%|███▌      | 413/1147 [03:02<05:14,  2.33it/s]

Парсинг новостей:  36%|███▌      | 414/1147 [03:02<05:22,  2.27it/s]

Парсинг новостей:  36%|███▌      | 415/1147 [03:03<05:08,  2.37it/s]

Парсинг новостей:  36%|███▋      | 416/1147 [03:03<05:16,  2.31it/s]

Парсинг новостей:  36%|███▋      | 417/1147 [03:04<05:20,  2.28it/s]

Парсинг новостей:  36%|███▋      | 418/1147 [03:04<05:20,  2.28it/s]

Парсинг новостей:  37%|███▋      | 419/1147 [03:05<05:23,  2.25it/s]

Парсинг новостей:  37%|███▋      | 420/1147 [03:05<05:25,  2.23it/s]

Парсинг новостей:  37%|███▋      | 421/1147 [03:06<05:32,  2.18it/s]

Парсинг новостей:  37%|███▋      | 422/1147 [03:06<05:15,  2.30it/s]

Парсинг новостей:  37%|███▋      | 423/1147 [03:06<05:01,  2.40it/s]

Парсинг новостей:  37%|███▋      | 424/1147 [03:07<05:00,  2.41it/s]

Парсинг новостей:  37%|███▋      | 425/1147 [03:07<05:20,  2.26it/s]

Парсинг новостей:  37%|███▋      | 426/1147 [03:08<05:30,  2.18it/s]

Парсинг новостей:  37%|███▋      | 427/1147 [03:08<05:43,  2.09it/s]

Парсинг новостей:  37%|███▋      | 428/1147 [03:09<05:43,  2.09it/s]

Парсинг новостей:  37%|███▋      | 429/1147 [03:09<05:50,  2.05it/s]

Парсинг новостей:  37%|███▋      | 430/1147 [03:10<05:33,  2.15it/s]

Парсинг новостей:  38%|███▊      | 431/1147 [03:10<05:18,  2.25it/s]

Парсинг новостей:  38%|███▊      | 432/1147 [03:10<05:04,  2.35it/s]

Парсинг новостей:  38%|███▊      | 433/1147 [03:11<05:58,  1.99it/s]

Парсинг новостей:  38%|███▊      | 434/1147 [03:12<05:35,  2.13it/s]

Парсинг новостей:  38%|███▊      | 435/1147 [03:12<05:38,  2.10it/s]

Парсинг новостей:  38%|███▊      | 436/1147 [03:13<05:46,  2.05it/s]

Парсинг новостей:  38%|███▊      | 437/1147 [03:13<05:35,  2.11it/s]

Парсинг новостей:  38%|███▊      | 438/1147 [03:13<05:33,  2.13it/s]

Парсинг новостей:  38%|███▊      | 439/1147 [03:14<05:17,  2.23it/s]

Парсинг новостей:  38%|███▊      | 440/1147 [03:14<05:08,  2.29it/s]

Парсинг новостей:  38%|███▊      | 441/1147 [03:15<05:01,  2.34it/s]

Парсинг новостей:  39%|███▊      | 442/1147 [03:15<05:09,  2.28it/s]

Парсинг новостей:  39%|███▊      | 443/1147 [03:16<05:21,  2.19it/s]

Парсинг новостей:  39%|███▊      | 444/1147 [03:16<05:36,  2.09it/s]

Парсинг новостей:  39%|███▉      | 445/1147 [03:17<06:33,  1.78it/s]

Парсинг новостей:  39%|███▉      | 446/1147 [03:17<06:10,  1.89it/s]

Парсинг новостей:  39%|███▉      | 447/1147 [03:18<06:37,  1.76it/s]

Парсинг новостей:  39%|███▉      | 448/1147 [03:18<05:57,  1.96it/s]

Парсинг новостей:  39%|███▉      | 449/1147 [03:19<05:31,  2.11it/s]

Парсинг новостей:  39%|███▉      | 450/1147 [03:19<05:34,  2.09it/s]

Парсинг новостей:  39%|███▉      | 451/1147 [03:20<05:09,  2.25it/s]

Парсинг новостей:  39%|███▉      | 452/1147 [03:20<05:00,  2.32it/s]

Парсинг новостей:  39%|███▉      | 453/1147 [03:20<04:46,  2.43it/s]

Парсинг новостей:  40%|███▉      | 454/1147 [03:21<04:47,  2.41it/s]

Парсинг новостей:  40%|███▉      | 455/1147 [03:21<04:41,  2.46it/s]

Парсинг новостей:  40%|███▉      | 456/1147 [03:22<04:35,  2.51it/s]

Парсинг новостей:  40%|███▉      | 457/1147 [03:22<04:33,  2.52it/s]

Парсинг новостей:  40%|███▉      | 458/1147 [03:22<04:43,  2.43it/s]

Парсинг новостей:  40%|████      | 459/1147 [03:23<04:50,  2.37it/s]

Парсинг новостей:  40%|████      | 460/1147 [03:23<04:38,  2.47it/s]

Парсинг новостей:  40%|████      | 461/1147 [03:24<04:29,  2.54it/s]

Парсинг новостей:  40%|████      | 462/1147 [03:24<04:35,  2.48it/s]

Парсинг новостей:  40%|████      | 463/1147 [03:24<04:43,  2.41it/s]

Парсинг новостей:  40%|████      | 464/1147 [03:25<04:45,  2.39it/s]

Парсинг новостей:  41%|████      | 465/1147 [03:25<04:40,  2.43it/s]

Парсинг новостей:  41%|████      | 466/1147 [03:26<04:33,  2.49it/s]

Парсинг новостей:  41%|████      | 467/1147 [03:26<04:48,  2.36it/s]

Парсинг новостей:  41%|████      | 468/1147 [03:27<04:49,  2.34it/s]

Парсинг новостей:  41%|████      | 469/1147 [03:27<04:42,  2.40it/s]

Парсинг новостей:  41%|████      | 470/1147 [03:27<04:34,  2.47it/s]

Парсинг новостей:  41%|████      | 471/1147 [03:28<04:30,  2.50it/s]

Парсинг новостей:  41%|████      | 472/1147 [03:28<04:40,  2.41it/s]

Парсинг новостей:  41%|████      | 473/1147 [03:29<04:46,  2.36it/s]

Парсинг новостей:  41%|████▏     | 474/1147 [03:29<04:39,  2.40it/s]

Парсинг новостей:  41%|████▏     | 475/1147 [03:30<04:49,  2.32it/s]

Парсинг новостей:  41%|████▏     | 476/1147 [03:30<04:37,  2.42it/s]

Парсинг новостей:  42%|████▏     | 477/1147 [03:30<04:39,  2.40it/s]

Парсинг новостей:  42%|████▏     | 478/1147 [03:31<04:43,  2.36it/s]

Парсинг новостей:  42%|████▏     | 479/1147 [03:31<04:36,  2.42it/s]

Парсинг новостей:  42%|████▏     | 480/1147 [03:32<04:31,  2.45it/s]

Парсинг новостей:  42%|████▏     | 481/1147 [03:32<04:31,  2.45it/s]

Парсинг новостей:  42%|████▏     | 482/1147 [03:32<04:33,  2.43it/s]

Парсинг новостей:  42%|████▏     | 483/1147 [03:33<04:28,  2.47it/s]

Парсинг новостей:  42%|████▏     | 484/1147 [03:33<04:25,  2.50it/s]

Парсинг новостей:  42%|████▏     | 485/1147 [03:34<04:23,  2.52it/s]

Парсинг новостей:  42%|████▏     | 486/1147 [03:34<05:22,  2.05it/s]

Парсинг новостей:  42%|████▏     | 487/1147 [03:35<05:09,  2.13it/s]

Парсинг новостей:  43%|████▎     | 488/1147 [03:35<04:56,  2.22it/s]

Парсинг новостей:  43%|████▎     | 489/1147 [03:36<04:56,  2.22it/s]

Парсинг новостей:  43%|████▎     | 490/1147 [03:36<04:41,  2.33it/s]

Парсинг новостей:  43%|████▎     | 491/1147 [03:37<05:32,  1.97it/s]

Парсинг новостей:  43%|████▎     | 492/1147 [03:37<05:25,  2.01it/s]

Парсинг новостей:  43%|████▎     | 493/1147 [03:37<05:06,  2.13it/s]

Парсинг новостей:  43%|████▎     | 494/1147 [03:38<04:51,  2.24it/s]

Парсинг новостей:  43%|████▎     | 495/1147 [03:38<04:42,  2.31it/s]

Парсинг новостей:  43%|████▎     | 496/1147 [03:39<05:33,  1.95it/s]

Парсинг новостей:  43%|████▎     | 497/1147 [03:39<05:16,  2.05it/s]

Парсинг новостей:  43%|████▎     | 498/1147 [03:40<04:56,  2.19it/s]

Парсинг новостей:  44%|████▎     | 499/1147 [03:40<05:03,  2.13it/s]

Парсинг новостей:  44%|████▎     | 500/1147 [03:41<05:16,  2.04it/s]

Парсинг новостей:  44%|████▎     | 501/1147 [03:41<05:20,  2.01it/s]

Парсинг новостей:  44%|████▍     | 502/1147 [03:42<05:15,  2.04it/s]

Парсинг новостей:  44%|████▍     | 503/1147 [03:42<04:54,  2.19it/s]

Парсинг новостей:  44%|████▍     | 504/1147 [03:43<04:42,  2.27it/s]

Парсинг новостей:  44%|████▍     | 505/1147 [03:43<04:43,  2.27it/s]

Парсинг новостей:  44%|████▍     | 506/1147 [03:44<04:52,  2.19it/s]

Парсинг новостей:  44%|████▍     | 507/1147 [03:44<05:01,  2.12it/s]

Парсинг новостей:  44%|████▍     | 508/1147 [03:44<05:02,  2.12it/s]

Парсинг новостей:  44%|████▍     | 509/1147 [03:45<05:01,  2.12it/s]

Парсинг новостей:  44%|████▍     | 510/1147 [03:46<06:01,  1.76it/s]

Парсинг новостей:  45%|████▍     | 511/1147 [03:46<05:32,  1.91it/s]

Парсинг новостей:  45%|████▍     | 512/1147 [03:47<05:16,  2.01it/s]

Парсинг новостей:  45%|████▍     | 513/1147 [03:47<06:06,  1.73it/s]

Парсинг новостей:  45%|████▍     | 514/1147 [03:48<05:56,  1.77it/s]

Парсинг новостей:  45%|████▍     | 515/1147 [03:48<05:21,  1.96it/s]

Парсинг новостей:  45%|████▍     | 516/1147 [03:49<05:00,  2.10it/s]

Парсинг новостей:  45%|████▌     | 517/1147 [03:49<04:58,  2.11it/s]

Парсинг новостей:  45%|████▌     | 518/1147 [03:50<04:42,  2.23it/s]

Парсинг новостей:  45%|████▌     | 519/1147 [03:50<04:32,  2.31it/s]

Парсинг новостей:  45%|████▌     | 520/1147 [03:51<05:43,  1.83it/s]

Парсинг новостей:  45%|████▌     | 521/1147 [03:51<05:30,  1.90it/s]

Парсинг новостей:  46%|████▌     | 522/1147 [03:52<05:23,  1.93it/s]

Парсинг новостей:  46%|████▌     | 523/1147 [03:52<05:24,  1.92it/s]

Парсинг новостей:  46%|████▌     | 524/1147 [03:53<05:12,  1.99it/s]

Парсинг новостей:  46%|████▌     | 525/1147 [03:53<05:04,  2.04it/s]

Парсинг новостей:  46%|████▌     | 526/1147 [03:54<04:45,  2.18it/s]

Парсинг новостей:  46%|████▌     | 527/1147 [03:54<04:31,  2.28it/s]

Парсинг новостей:  46%|████▌     | 528/1147 [03:54<04:30,  2.29it/s]

Парсинг новостей:  46%|████▌     | 529/1147 [03:55<04:22,  2.36it/s]

Парсинг новостей:  46%|████▌     | 530/1147 [03:55<04:14,  2.42it/s]

Парсинг новостей:  46%|████▋     | 531/1147 [03:56<04:05,  2.51it/s]

Парсинг новостей:  46%|████▋     | 532/1147 [03:56<04:54,  2.09it/s]

Парсинг новостей:  46%|████▋     | 533/1147 [03:57<04:36,  2.22it/s]

Парсинг новостей:  47%|████▋     | 534/1147 [03:57<04:32,  2.25it/s]

Парсинг новостей:  47%|████▋     | 535/1147 [03:58<05:48,  1.75it/s]

Парсинг новостей:  47%|████▋     | 536/1147 [03:59<06:04,  1.68it/s]

Парсинг новостей:  47%|████▋     | 537/1147 [03:59<05:30,  1.85it/s]

Парсинг новостей:  47%|████▋     | 538/1147 [03:59<05:01,  2.02it/s]

Парсинг новостей:  47%|████▋     | 539/1147 [04:00<04:48,  2.11it/s]

Парсинг новостей:  47%|████▋     | 540/1147 [04:00<04:47,  2.11it/s]

Парсинг новостей:  47%|████▋     | 541/1147 [04:01<04:43,  2.14it/s]

Парсинг новостей:  47%|████▋     | 542/1147 [04:01<04:50,  2.08it/s]

Парсинг новостей:  47%|████▋     | 543/1147 [04:02<04:51,  2.07it/s]

Парсинг новостей:  47%|████▋     | 544/1147 [04:02<04:28,  2.25it/s]

Парсинг новостей:  48%|████▊     | 545/1147 [04:02<04:24,  2.28it/s]

Парсинг новостей:  48%|████▊     | 546/1147 [04:03<04:13,  2.37it/s]

Парсинг новостей:  48%|████▊     | 547/1147 [04:04<05:03,  1.98it/s]

Парсинг новостей:  48%|████▊     | 548/1147 [04:04<04:46,  2.09it/s]

Парсинг новостей:  48%|████▊     | 549/1147 [04:04<04:39,  2.14it/s]

Парсинг новостей:  48%|████▊     | 550/1147 [04:05<04:47,  2.08it/s]

Парсинг новостей:  48%|████▊     | 551/1147 [04:05<04:40,  2.12it/s]

Парсинг новостей:  48%|████▊     | 552/1147 [04:06<04:21,  2.28it/s]

Парсинг новостей:  48%|████▊     | 553/1147 [04:06<05:02,  1.97it/s]

Парсинг новостей:  48%|████▊     | 554/1147 [04:07<05:42,  1.73it/s]

Парсинг новостей:  48%|████▊     | 555/1147 [04:08<05:14,  1.88it/s]

Парсинг новостей:  48%|████▊     | 556/1147 [04:08<05:09,  1.91it/s]

Парсинг новостей:  49%|████▊     | 557/1147 [04:09<05:04,  1.94it/s]

Парсинг новостей:  49%|████▊     | 558/1147 [04:09<05:58,  1.64it/s]

Парсинг новостей:  49%|████▊     | 559/1147 [04:10<05:22,  1.82it/s]

Парсинг новостей:  49%|████▉     | 560/1147 [04:10<04:49,  2.02it/s]

Парсинг новостей:  49%|████▉     | 561/1147 [04:11<04:41,  2.08it/s]

Парсинг новостей:  49%|████▉     | 562/1147 [04:11<04:24,  2.21it/s]

Парсинг новостей:  49%|████▉     | 563/1147 [04:11<04:10,  2.33it/s]

Парсинг новостей:  49%|████▉     | 564/1147 [04:12<04:12,  2.31it/s]

Парсинг новостей:  49%|████▉     | 565/1147 [04:12<04:13,  2.30it/s]

Парсинг новостей:  49%|████▉     | 566/1147 [04:13<04:12,  2.30it/s]

Парсинг новостей:  49%|████▉     | 567/1147 [04:13<04:05,  2.37it/s]

Парсинг новостей:  50%|████▉     | 568/1147 [04:14<04:04,  2.37it/s]

Парсинг новостей:  50%|████▉     | 569/1147 [04:14<04:03,  2.37it/s]

Парсинг новостей:  50%|████▉     | 570/1147 [04:14<04:05,  2.35it/s]

Парсинг новостей:  50%|████▉     | 571/1147 [04:15<04:09,  2.31it/s]

Парсинг новостей:  50%|████▉     | 572/1147 [04:15<03:57,  2.42it/s]

Парсинг новостей:  50%|████▉     | 573/1147 [04:16<03:50,  2.49it/s]

Парсинг новостей:  50%|█████     | 574/1147 [04:16<03:43,  2.56it/s]

Парсинг новостей:  50%|█████     | 575/1147 [04:16<04:05,  2.33it/s]

Парсинг новостей:  50%|█████     | 576/1147 [04:17<04:11,  2.27it/s]

Парсинг новостей:  50%|█████     | 577/1147 [04:17<04:06,  2.32it/s]

Парсинг новостей:  50%|█████     | 578/1147 [04:18<03:58,  2.39it/s]

Парсинг новостей:  50%|█████     | 579/1147 [04:18<03:58,  2.38it/s]

Парсинг новостей:  51%|█████     | 580/1147 [04:19<04:08,  2.28it/s]

Парсинг новостей:  51%|█████     | 581/1147 [04:19<04:14,  2.22it/s]

Парсинг новостей:  51%|█████     | 582/1147 [04:20<04:16,  2.20it/s]

Парсинг новостей:  51%|█████     | 583/1147 [04:20<04:00,  2.34it/s]

Парсинг новостей:  51%|█████     | 584/1147 [04:20<03:58,  2.36it/s]

Парсинг новостей:  51%|█████     | 585/1147 [04:21<03:55,  2.39it/s]

Парсинг новостей:  51%|█████     | 586/1147 [04:21<04:08,  2.26it/s]

Парсинг новостей:  51%|█████     | 587/1147 [04:22<04:21,  2.14it/s]

Парсинг новостей:  51%|█████▏    | 588/1147 [04:22<04:23,  2.12it/s]

Парсинг новостей:  51%|█████▏    | 589/1147 [04:23<04:17,  2.17it/s]

Парсинг новостей:  51%|█████▏    | 590/1147 [04:23<04:08,  2.24it/s]

Парсинг новостей:  52%|█████▏    | 591/1147 [04:24<04:02,  2.29it/s]

Парсинг новостей:  52%|█████▏    | 592/1147 [04:24<03:52,  2.38it/s]

Парсинг новостей:  52%|█████▏    | 593/1147 [04:24<03:57,  2.33it/s]

Парсинг новостей:  52%|█████▏    | 594/1147 [04:25<03:58,  2.31it/s]

Парсинг новостей:  52%|█████▏    | 595/1147 [04:25<03:47,  2.42it/s]

Парсинг новостей:  52%|█████▏    | 596/1147 [04:25<03:35,  2.56it/s]

Парсинг новостей:  52%|█████▏    | 597/1147 [04:26<03:40,  2.49it/s]

Парсинг новостей:  52%|█████▏    | 598/1147 [04:26<03:51,  2.38it/s]

Парсинг новостей:  52%|█████▏    | 599/1147 [04:27<03:59,  2.29it/s]

Парсинг новостей:  52%|█████▏    | 600/1147 [04:27<04:03,  2.25it/s]

Парсинг новостей:  52%|█████▏    | 601/1147 [04:28<04:08,  2.20it/s]

Парсинг новостей:  52%|█████▏    | 602/1147 [04:28<03:58,  2.28it/s]

Парсинг новостей:  53%|█████▎    | 603/1147 [04:29<03:59,  2.27it/s]

Парсинг новостей:  53%|█████▎    | 604/1147 [04:29<03:57,  2.29it/s]

Парсинг новостей:  53%|█████▎    | 605/1147 [04:30<04:02,  2.23it/s]

Парсинг новостей:  53%|█████▎    | 606/1147 [04:30<04:04,  2.21it/s]

Парсинг новостей:  53%|█████▎    | 607/1147 [04:30<03:57,  2.28it/s]

Парсинг новостей:  53%|█████▎    | 608/1147 [04:31<03:54,  2.30it/s]

Парсинг новостей:  53%|█████▎    | 609/1147 [04:31<03:48,  2.36it/s]

Парсинг новостей:  53%|█████▎    | 610/1147 [04:32<03:54,  2.29it/s]

Парсинг новостей:  53%|█████▎    | 611/1147 [04:32<03:53,  2.29it/s]

Парсинг новостей:  53%|█████▎    | 612/1147 [04:33<03:46,  2.36it/s]

Парсинг новостей:  53%|█████▎    | 613/1147 [04:33<03:39,  2.43it/s]

Парсинг новостей:  54%|█████▎    | 614/1147 [04:33<03:42,  2.40it/s]

Парсинг новостей:  54%|█████▎    | 615/1147 [04:34<03:53,  2.28it/s]

Парсинг новостей:  54%|█████▎    | 616/1147 [04:35<04:36,  1.92it/s]

Парсинг новостей:  54%|█████▍    | 617/1147 [04:35<04:37,  1.91it/s]

Парсинг новостей:  54%|█████▍    | 618/1147 [04:35<04:17,  2.05it/s]

Парсинг новостей:  54%|█████▍    | 619/1147 [04:36<04:02,  2.17it/s]

Парсинг новостей:  54%|█████▍    | 620/1147 [04:36<04:04,  2.15it/s]

Парсинг новостей:  54%|█████▍    | 621/1147 [04:37<04:56,  1.77it/s]

Парсинг новостей:  54%|█████▍    | 622/1147 [04:38<05:20,  1.64it/s]

Парсинг новостей:  54%|█████▍    | 623/1147 [04:38<04:46,  1.83it/s]

Парсинг новостей:  54%|█████▍    | 624/1147 [04:39<04:23,  1.98it/s]

Парсинг новостей:  54%|█████▍    | 625/1147 [04:39<04:27,  1.95it/s]

Парсинг новостей:  55%|█████▍    | 626/1147 [04:40<04:13,  2.06it/s]

Парсинг новостей:  55%|█████▍    | 627/1147 [04:40<04:09,  2.08it/s]

Парсинг новостей:  55%|█████▍    | 628/1147 [04:41<04:02,  2.14it/s]

Парсинг новостей:  55%|█████▍    | 629/1147 [04:41<04:03,  2.13it/s]

Парсинг новостей:  55%|█████▍    | 630/1147 [04:41<03:50,  2.25it/s]

Парсинг новостей:  55%|█████▌    | 631/1147 [04:42<03:46,  2.28it/s]

Парсинг новостей:  55%|█████▌    | 632/1147 [04:42<03:38,  2.35it/s]

Парсинг новостей:  55%|█████▌    | 633/1147 [04:43<03:56,  2.18it/s]

Парсинг новостей:  55%|█████▌    | 634/1147 [04:43<03:58,  2.15it/s]

Парсинг новостей:  55%|█████▌    | 635/1147 [04:44<03:57,  2.15it/s]

Парсинг новостей:  55%|█████▌    | 636/1147 [04:44<04:00,  2.12it/s]

Парсинг новостей:  56%|█████▌    | 637/1147 [04:45<03:50,  2.21it/s]

Парсинг новостей:  56%|█████▌    | 638/1147 [04:45<03:50,  2.21it/s]

Парсинг новостей:  56%|█████▌    | 639/1147 [04:45<03:41,  2.29it/s]

Парсинг новостей:  56%|█████▌    | 640/1147 [04:46<03:35,  2.35it/s]

Парсинг новостей:  56%|█████▌    | 641/1147 [04:46<03:36,  2.33it/s]

Парсинг новостей:  56%|█████▌    | 642/1147 [04:47<03:31,  2.39it/s]

Парсинг новостей:  56%|█████▌    | 643/1147 [04:47<03:31,  2.38it/s]

Парсинг новостей:  56%|█████▌    | 644/1147 [04:47<03:25,  2.44it/s]

Парсинг новостей:  56%|█████▌    | 645/1147 [04:48<03:39,  2.29it/s]

Парсинг новостей:  56%|█████▋    | 646/1147 [04:48<03:44,  2.23it/s]

Парсинг новостей:  56%|█████▋    | 647/1147 [04:49<03:49,  2.18it/s]

Парсинг новостей:  56%|█████▋    | 648/1147 [04:49<03:52,  2.15it/s]

Парсинг новостей:  57%|█████▋    | 649/1147 [04:50<03:57,  2.09it/s]

Парсинг новостей:  57%|█████▋    | 650/1147 [04:50<03:54,  2.12it/s]

Парсинг новостей:  57%|█████▋    | 651/1147 [04:51<03:42,  2.23it/s]

Парсинг новостей:  57%|█████▋    | 652/1147 [04:51<03:29,  2.37it/s]

Парсинг новостей:  57%|█████▋    | 653/1147 [04:52<03:36,  2.29it/s]

Парсинг новостей:  57%|█████▋    | 654/1147 [04:52<03:40,  2.23it/s]

Парсинг новостей:  57%|█████▋    | 655/1147 [04:53<03:45,  2.18it/s]

Парсинг новостей:  57%|█████▋    | 656/1147 [04:53<03:53,  2.11it/s]

Парсинг новостей:  57%|█████▋    | 657/1147 [04:53<03:44,  2.18it/s]

Парсинг новостей:  57%|█████▋    | 658/1147 [04:54<03:35,  2.27it/s]

Парсинг новостей:  57%|█████▋    | 659/1147 [04:54<03:28,  2.34it/s]

Парсинг новостей:  58%|█████▊    | 660/1147 [04:55<03:33,  2.28it/s]

Парсинг новостей:  58%|█████▊    | 661/1147 [04:55<03:36,  2.24it/s]

Парсинг новостей:  58%|█████▊    | 662/1147 [04:56<03:40,  2.20it/s]

Парсинг новостей:  58%|█████▊    | 663/1147 [04:56<03:29,  2.31it/s]

Парсинг новостей:  58%|█████▊    | 664/1147 [04:56<03:22,  2.38it/s]

Парсинг новостей:  58%|█████▊    | 665/1147 [04:57<03:20,  2.41it/s]

Парсинг новостей:  58%|█████▊    | 666/1147 [04:57<03:28,  2.30it/s]

Парсинг новостей:  58%|█████▊    | 667/1147 [04:58<03:35,  2.23it/s]

Парсинг новостей:  58%|█████▊    | 668/1147 [04:58<03:43,  2.14it/s]

Парсинг новостей:  58%|█████▊    | 669/1147 [04:59<03:49,  2.08it/s]

Парсинг новостей:  58%|█████▊    | 670/1147 [04:59<03:55,  2.03it/s]

Парсинг новостей:  59%|█████▊    | 671/1147 [05:00<03:43,  2.13it/s]

Парсинг новостей:  59%|█████▊    | 672/1147 [05:00<03:33,  2.22it/s]

Парсинг новостей:  59%|█████▊    | 673/1147 [05:01<03:36,  2.19it/s]

Парсинг новостей:  59%|█████▉    | 674/1147 [05:01<03:38,  2.16it/s]

Парсинг новостей:  59%|█████▉    | 675/1147 [05:02<04:16,  1.84it/s]

Парсинг новостей:  59%|█████▉    | 676/1147 [05:02<03:54,  2.01it/s]

Парсинг новостей:  59%|█████▉    | 677/1147 [05:03<03:38,  2.15it/s]

Парсинг новостей:  59%|█████▉    | 678/1147 [05:03<03:41,  2.12it/s]

Парсинг новостей:  59%|█████▉    | 679/1147 [05:04<03:43,  2.10it/s]

Парсинг новостей:  59%|█████▉    | 680/1147 [05:04<03:41,  2.11it/s]

Парсинг новостей:  59%|█████▉    | 681/1147 [05:04<03:31,  2.20it/s]

Парсинг новостей:  59%|█████▉    | 682/1147 [05:05<03:27,  2.24it/s]

Парсинг новостей:  60%|█████▉    | 683/1147 [05:05<03:24,  2.27it/s]

Парсинг новостей:  60%|█████▉    | 684/1147 [05:06<03:21,  2.30it/s]

Парсинг новостей:  60%|█████▉    | 685/1147 [05:06<03:22,  2.28it/s]

Парсинг новостей:  60%|█████▉    | 686/1147 [05:07<03:26,  2.23it/s]

Парсинг новостей:  60%|█████▉    | 687/1147 [05:07<03:48,  2.01it/s]

Парсинг новостей:  60%|█████▉    | 688/1147 [05:08<03:44,  2.04it/s]

Парсинг новостей:  60%|██████    | 689/1147 [05:08<03:44,  2.04it/s]

Парсинг новостей:  60%|██████    | 690/1147 [05:09<03:47,  2.01it/s]

Парсинг новостей:  60%|██████    | 691/1147 [05:09<03:36,  2.11it/s]

Парсинг новостей:  60%|██████    | 692/1147 [05:10<03:23,  2.24it/s]

Парсинг новостей:  60%|██████    | 693/1147 [05:10<03:15,  2.32it/s]

Парсинг новостей:  61%|██████    | 694/1147 [05:10<03:11,  2.36it/s]

Парсинг новостей:  61%|██████    | 695/1147 [05:11<03:07,  2.41it/s]

Парсинг новостей:  61%|██████    | 696/1147 [05:11<03:03,  2.46it/s]

Парсинг новостей:  61%|██████    | 697/1147 [05:12<02:58,  2.53it/s]

Парсинг новостей:  61%|██████    | 698/1147 [05:12<03:00,  2.49it/s]

Парсинг новостей:  61%|██████    | 699/1147 [05:12<02:59,  2.49it/s]

Парсинг новостей:  61%|██████    | 700/1147 [05:13<03:07,  2.39it/s]

Парсинг новостей:  61%|██████    | 701/1147 [05:13<03:02,  2.45it/s]

Парсинг новостей:  61%|██████    | 702/1147 [05:14<02:57,  2.50it/s]

Парсинг новостей:  61%|██████▏   | 703/1147 [05:14<03:04,  2.40it/s]

Парсинг новостей:  61%|██████▏   | 704/1147 [05:14<02:55,  2.53it/s]

Парсинг новостей:  61%|██████▏   | 705/1147 [05:15<02:54,  2.54it/s]

Парсинг новостей:  62%|██████▏   | 706/1147 [05:15<03:01,  2.44it/s]

Парсинг новостей:  62%|██████▏   | 707/1147 [05:16<03:05,  2.37it/s]

Парсинг новостей:  62%|██████▏   | 708/1147 [05:16<03:13,  2.27it/s]

Парсинг новостей:  62%|██████▏   | 709/1147 [05:17<03:21,  2.18it/s]

Парсинг новостей:  62%|██████▏   | 710/1147 [05:17<04:09,  1.76it/s]

Парсинг новостей:  62%|██████▏   | 711/1147 [05:18<03:47,  1.92it/s]

Парсинг новостей:  62%|██████▏   | 712/1147 [05:19<05:19,  1.36it/s]

Парсинг новостей:  62%|██████▏   | 713/1147 [05:20<04:39,  1.55it/s]

Парсинг новостей:  62%|██████▏   | 714/1147 [05:20<04:04,  1.77it/s]

Парсинг новостей:  62%|██████▏   | 715/1147 [05:20<03:50,  1.87it/s]

Парсинг новостей:  62%|██████▏   | 716/1147 [05:21<03:43,  1.93it/s]

Парсинг новостей:  63%|██████▎   | 717/1147 [05:21<03:39,  1.96it/s]

Парсинг новостей:  63%|██████▎   | 718/1147 [05:22<03:57,  1.81it/s]

Парсинг новостей:  63%|██████▎   | 719/1147 [05:23<03:50,  1.86it/s]

Парсинг новостей:  63%|██████▎   | 720/1147 [05:23<03:45,  1.89it/s]

Парсинг новостей:  63%|██████▎   | 721/1147 [05:24<03:38,  1.95it/s]

Парсинг новостей:  63%|██████▎   | 722/1147 [05:24<03:34,  1.98it/s]

Парсинг новостей:  63%|██████▎   | 723/1147 [05:25<03:54,  1.80it/s]

Парсинг новостей:  63%|██████▎   | 724/1147 [05:25<03:47,  1.86it/s]

Парсинг новостей:  63%|██████▎   | 725/1147 [05:26<03:48,  1.85it/s]

Парсинг новостей:  63%|██████▎   | 726/1147 [05:26<03:36,  1.94it/s]

Парсинг новостей:  63%|██████▎   | 727/1147 [05:27<03:27,  2.02it/s]

Парсинг новостей:  63%|██████▎   | 728/1147 [05:27<03:12,  2.18it/s]

Парсинг новостей:  64%|██████▎   | 729/1147 [05:27<03:03,  2.28it/s]

Парсинг новостей:  64%|██████▎   | 730/1147 [05:28<02:56,  2.37it/s]

Парсинг новостей:  64%|██████▎   | 731/1147 [05:28<03:00,  2.30it/s]

Парсинг новостей:  64%|██████▍   | 732/1147 [05:29<03:11,  2.17it/s]

Парсинг новостей:  64%|██████▍   | 733/1147 [05:29<03:14,  2.13it/s]

Парсинг новостей:  64%|██████▍   | 734/1147 [05:30<03:03,  2.25it/s]

Парсинг новостей:  64%|██████▍   | 735/1147 [05:30<02:58,  2.31it/s]

Парсинг новостей:  64%|██████▍   | 736/1147 [05:30<02:52,  2.38it/s]

Парсинг новостей:  64%|██████▍   | 737/1147 [05:31<02:54,  2.35it/s]

Парсинг новостей:  64%|██████▍   | 738/1147 [05:31<03:01,  2.25it/s]

Парсинг новостей:  64%|██████▍   | 739/1147 [05:32<02:57,  2.29it/s]

Парсинг новостей:  65%|██████▍   | 740/1147 [05:32<03:02,  2.23it/s]

Парсинг новостей:  65%|██████▍   | 741/1147 [05:33<03:06,  2.18it/s]

Парсинг новостей:  65%|██████▍   | 742/1147 [05:33<03:00,  2.24it/s]

Парсинг новостей:  65%|██████▍   | 743/1147 [05:34<02:54,  2.31it/s]

Парсинг новостей:  65%|██████▍   | 744/1147 [05:34<02:53,  2.32it/s]

Парсинг новостей:  65%|██████▍   | 745/1147 [05:34<02:47,  2.40it/s]

Парсинг новостей:  65%|██████▌   | 746/1147 [05:35<02:51,  2.34it/s]

Парсинг новостей:  65%|██████▌   | 747/1147 [05:35<02:54,  2.29it/s]

Парсинг новостей:  65%|██████▌   | 748/1147 [05:36<02:51,  2.32it/s]

Парсинг новостей:  65%|██████▌   | 749/1147 [05:36<02:57,  2.24it/s]

Парсинг новостей:  65%|██████▌   | 750/1147 [05:37<03:05,  2.14it/s]

Парсинг новостей:  65%|██████▌   | 751/1147 [05:37<03:02,  2.17it/s]

Парсинг новостей:  66%|██████▌   | 752/1147 [05:38<03:06,  2.12it/s]

Парсинг новостей:  66%|██████▌   | 753/1147 [05:38<02:57,  2.22it/s]

Парсинг новостей:  66%|██████▌   | 754/1147 [05:38<02:49,  2.32it/s]

Парсинг новостей:  66%|██████▌   | 755/1147 [05:39<02:43,  2.40it/s]

Парсинг новостей:  66%|██████▌   | 756/1147 [05:39<02:47,  2.34it/s]

Парсинг новостей:  66%|██████▌   | 757/1147 [05:40<02:53,  2.25it/s]

Парсинг новостей:  66%|██████▌   | 758/1147 [05:40<02:45,  2.36it/s]

Парсинг новостей:  66%|██████▌   | 759/1147 [05:41<02:41,  2.41it/s]

Парсинг новостей:  66%|██████▋   | 760/1147 [05:41<02:39,  2.42it/s]

Парсинг новостей:  66%|██████▋   | 761/1147 [05:41<02:45,  2.34it/s]

Парсинг новостей:  66%|██████▋   | 762/1147 [05:42<02:53,  2.22it/s]

Парсинг новостей:  67%|██████▋   | 763/1147 [05:42<03:00,  2.13it/s]

Парсинг новостей:  67%|██████▋   | 764/1147 [05:43<03:00,  2.12it/s]

Парсинг новостей:  67%|██████▋   | 765/1147 [05:43<02:50,  2.24it/s]

Парсинг новостей:  67%|██████▋   | 766/1147 [05:44<02:45,  2.31it/s]

Парсинг новостей:  67%|██████▋   | 767/1147 [05:44<02:58,  2.13it/s]

Парсинг новостей:  67%|██████▋   | 768/1147 [05:45<02:50,  2.22it/s]

Парсинг новостей:  67%|██████▋   | 769/1147 [05:45<02:58,  2.12it/s]

Парсинг новостей:  67%|██████▋   | 770/1147 [05:46<02:57,  2.12it/s]

Парсинг новостей:  67%|██████▋   | 771/1147 [05:46<02:56,  2.13it/s]

Парсинг новостей:  67%|██████▋   | 772/1147 [05:47<02:58,  2.10it/s]

Парсинг новостей:  67%|██████▋   | 773/1147 [05:47<03:02,  2.05it/s]

Парсинг новостей:  67%|██████▋   | 774/1147 [05:47<02:50,  2.19it/s]

Парсинг новостей:  68%|██████▊   | 775/1147 [05:48<02:50,  2.19it/s]

Парсинг новостей:  68%|██████▊   | 776/1147 [05:49<03:26,  1.79it/s]

Парсинг новостей:  68%|██████▊   | 777/1147 [05:49<03:19,  1.85it/s]

Парсинг новостей:  68%|██████▊   | 778/1147 [05:50<03:17,  1.87it/s]

Парсинг новостей:  68%|██████▊   | 779/1147 [05:50<03:13,  1.90it/s]

Парсинг новостей:  68%|██████▊   | 780/1147 [05:51<03:10,  1.93it/s]

Парсинг новостей:  68%|██████▊   | 781/1147 [05:51<02:58,  2.05it/s]

Парсинг новостей:  68%|██████▊   | 782/1147 [05:52<02:51,  2.12it/s]

Парсинг новостей:  68%|██████▊   | 783/1147 [05:52<02:47,  2.17it/s]

Парсинг новостей:  68%|██████▊   | 784/1147 [05:52<02:42,  2.23it/s]

Парсинг новостей:  68%|██████▊   | 785/1147 [05:53<02:47,  2.16it/s]

Парсинг новостей:  69%|██████▊   | 786/1147 [05:53<02:47,  2.15it/s]

Парсинг новостей:  69%|██████▊   | 787/1147 [05:54<02:47,  2.15it/s]

Парсинг новостей:  69%|██████▊   | 788/1147 [05:54<02:38,  2.26it/s]

Парсинг новостей:  69%|██████▉   | 789/1147 [05:55<02:38,  2.26it/s]

Парсинг новостей:  69%|██████▉   | 790/1147 [05:55<02:34,  2.31it/s]

Парсинг новостей:  69%|██████▉   | 791/1147 [05:56<02:39,  2.23it/s]

Парсинг новостей:  69%|██████▉   | 792/1147 [05:56<02:42,  2.18it/s]

Парсинг новостей:  69%|██████▉   | 793/1147 [05:57<02:47,  2.11it/s]

Парсинг новостей:  69%|██████▉   | 794/1147 [05:57<02:54,  2.02it/s]

Парсинг новостей:  69%|██████▉   | 795/1147 [05:58<02:51,  2.06it/s]

Парсинг новостей:  69%|██████▉   | 796/1147 [05:58<02:49,  2.07it/s]

Парсинг новостей:  69%|██████▉   | 797/1147 [05:58<02:40,  2.18it/s]

Парсинг новостей:  70%|██████▉   | 798/1147 [05:59<02:44,  2.12it/s]

Парсинг новостей:  70%|██████▉   | 799/1147 [05:59<02:44,  2.12it/s]

Парсинг новостей:  70%|██████▉   | 800/1147 [06:00<02:44,  2.11it/s]

Парсинг новостей:  70%|██████▉   | 801/1147 [06:00<02:32,  2.27it/s]

Парсинг новостей:  70%|██████▉   | 802/1147 [06:01<02:29,  2.30it/s]

Парсинг новостей:  70%|███████   | 803/1147 [06:01<02:25,  2.37it/s]

Парсинг новостей:  70%|███████   | 804/1147 [06:02<02:24,  2.37it/s]

Парсинг новостей:  70%|███████   | 805/1147 [06:02<02:21,  2.41it/s]

Парсинг новостей:  70%|███████   | 806/1147 [06:02<02:24,  2.36it/s]

Парсинг новостей:  70%|███████   | 807/1147 [06:03<02:32,  2.22it/s]

Парсинг новостей:  70%|███████   | 808/1147 [06:03<02:37,  2.15it/s]

Парсинг новостей:  71%|███████   | 809/1147 [06:04<02:41,  2.09it/s]

Парсинг новостей:  71%|███████   | 810/1147 [06:04<02:42,  2.08it/s]

Парсинг новостей:  71%|███████   | 811/1147 [06:05<02:44,  2.05it/s]

Парсинг новостей:  71%|███████   | 812/1147 [06:05<02:38,  2.12it/s]

Парсинг новостей:  71%|███████   | 813/1147 [06:06<02:33,  2.18it/s]

Парсинг новостей:  71%|███████   | 814/1147 [06:06<02:24,  2.31it/s]

Парсинг новостей:  71%|███████   | 815/1147 [06:07<02:31,  2.19it/s]

Парсинг новостей:  71%|███████   | 816/1147 [06:07<02:33,  2.16it/s]

Парсинг новостей:  71%|███████   | 817/1147 [06:08<02:32,  2.17it/s]

Парсинг новостей:  71%|███████▏  | 818/1147 [06:08<02:59,  1.83it/s]

Парсинг новостей:  71%|███████▏  | 819/1147 [06:09<02:45,  1.98it/s]

Парсинг новостей:  71%|███████▏  | 820/1147 [06:09<02:41,  2.03it/s]

Парсинг новостей:  72%|███████▏  | 821/1147 [06:10<02:35,  2.10it/s]

Парсинг новостей:  72%|███████▏  | 822/1147 [06:10<02:24,  2.26it/s]

Парсинг новостей:  72%|███████▏  | 823/1147 [06:10<02:17,  2.35it/s]

Парсинг новостей:  72%|███████▏  | 824/1147 [06:11<02:13,  2.41it/s]

Парсинг новостей:  72%|███████▏  | 825/1147 [06:11<02:22,  2.25it/s]

Парсинг новостей:  72%|███████▏  | 826/1147 [06:13<04:02,  1.32it/s]

Парсинг новостей:  72%|███████▏  | 827/1147 [06:13<03:40,  1.45it/s]

Парсинг новостей:  72%|███████▏  | 828/1147 [06:14<03:13,  1.65it/s]

Парсинг новостей:  72%|███████▏  | 829/1147 [06:14<02:53,  1.83it/s]

Парсинг новостей:  72%|███████▏  | 830/1147 [06:15<02:44,  1.93it/s]

Парсинг новостей:  72%|███████▏  | 831/1147 [06:15<02:35,  2.03it/s]

Парсинг новостей:  73%|███████▎  | 832/1147 [06:15<02:31,  2.07it/s]

Парсинг новостей:  73%|███████▎  | 833/1147 [06:16<02:31,  2.07it/s]

Парсинг новостей:  73%|███████▎  | 834/1147 [06:16<02:31,  2.07it/s]

Парсинг новостей:  73%|███████▎  | 835/1147 [06:17<02:35,  2.01it/s]

Парсинг новостей:  73%|███████▎  | 836/1147 [06:18<02:41,  1.93it/s]

Парсинг новостей:  73%|███████▎  | 837/1147 [06:18<02:40,  1.93it/s]

Парсинг новостей:  73%|███████▎  | 838/1147 [06:19<02:40,  1.93it/s]

Парсинг новостей:  73%|███████▎  | 839/1147 [06:19<02:36,  1.96it/s]

Парсинг новостей:  73%|███████▎  | 840/1147 [06:19<02:27,  2.07it/s]

Парсинг новостей:  73%|███████▎  | 841/1147 [06:20<02:20,  2.18it/s]

Парсинг новостей:  73%|███████▎  | 842/1147 [06:20<02:21,  2.16it/s]

Парсинг новостей:  73%|███████▎  | 843/1147 [06:21<02:20,  2.17it/s]

Парсинг новостей:  74%|███████▎  | 844/1147 [06:21<02:21,  2.15it/s]

Парсинг новостей:  74%|███████▎  | 845/1147 [06:22<02:24,  2.09it/s]

Парсинг новостей:  74%|███████▍  | 846/1147 [06:22<02:19,  2.16it/s]

Парсинг новостей:  74%|███████▍  | 847/1147 [06:23<02:25,  2.07it/s]

Парсинг новостей:  74%|███████▍  | 848/1147 [06:23<02:15,  2.20it/s]

Парсинг новостей:  74%|███████▍  | 849/1147 [06:24<02:10,  2.27it/s]

Парсинг новостей:  74%|███████▍  | 850/1147 [06:24<02:12,  2.25it/s]

Парсинг новостей:  74%|███████▍  | 851/1147 [06:24<02:09,  2.28it/s]

Парсинг новостей:  74%|███████▍  | 852/1147 [06:25<02:11,  2.25it/s]

Парсинг новостей:  74%|███████▍  | 853/1147 [06:25<02:14,  2.19it/s]

Парсинг новостей:  74%|███████▍  | 854/1147 [06:26<02:18,  2.12it/s]

Парсинг новостей:  75%|███████▍  | 855/1147 [06:26<02:10,  2.24it/s]

Парсинг новостей:  75%|███████▍  | 856/1147 [06:27<02:04,  2.34it/s]

Парсинг новостей:  75%|███████▍  | 857/1147 [06:27<02:01,  2.40it/s]

Парсинг новостей:  75%|███████▍  | 858/1147 [06:28<02:07,  2.27it/s]

Парсинг новостей:  75%|███████▍  | 859/1147 [06:28<02:14,  2.13it/s]

Парсинг новостей:  75%|███████▍  | 860/1147 [06:29<02:17,  2.08it/s]

Парсинг новостей:  75%|███████▌  | 861/1147 [06:29<02:19,  2.05it/s]

Парсинг новостей:  75%|███████▌  | 862/1147 [06:30<02:18,  2.06it/s]

Парсинг новостей:  75%|███████▌  | 863/1147 [06:30<02:09,  2.19it/s]

Парсинг новостей:  75%|███████▌  | 864/1147 [06:30<02:02,  2.30it/s]

Парсинг новостей:  75%|███████▌  | 865/1147 [06:31<01:59,  2.36it/s]

Парсинг новостей:  76%|███████▌  | 866/1147 [06:31<01:58,  2.38it/s]

Парсинг новостей:  76%|███████▌  | 867/1147 [06:32<01:55,  2.42it/s]

Парсинг новостей:  76%|███████▌  | 868/1147 [06:32<01:53,  2.45it/s]

Парсинг новостей:  76%|███████▌  | 869/1147 [06:32<01:53,  2.46it/s]

Парсинг новостей:  76%|███████▌  | 870/1147 [06:33<01:58,  2.34it/s]

Парсинг новостей:  76%|███████▌  | 871/1147 [06:33<02:00,  2.29it/s]

Парсинг новостей:  76%|███████▌  | 872/1147 [06:34<02:01,  2.26it/s]

Парсинг новостей:  76%|███████▌  | 873/1147 [06:34<01:57,  2.34it/s]

Парсинг новостей:  76%|███████▌  | 874/1147 [06:35<01:54,  2.37it/s]

Парсинг новостей:  76%|███████▋  | 875/1147 [06:35<02:00,  2.25it/s]

Парсинг новостей:  76%|███████▋  | 876/1147 [06:35<01:58,  2.28it/s]

Парсинг новостей:  76%|███████▋  | 877/1147 [06:36<02:02,  2.20it/s]

Парсинг новостей:  77%|███████▋  | 878/1147 [06:36<02:05,  2.15it/s]

Парсинг новостей:  77%|███████▋  | 879/1147 [06:37<02:07,  2.10it/s]

Парсинг новостей:  77%|███████▋  | 880/1147 [06:37<02:08,  2.09it/s]

Парсинг новостей:  77%|███████▋  | 881/1147 [06:38<02:09,  2.05it/s]

Парсинг новостей:  77%|███████▋  | 882/1147 [06:38<02:00,  2.19it/s]

Парсинг новостей:  77%|███████▋  | 883/1147 [06:39<01:57,  2.25it/s]

Парсинг новостей:  77%|███████▋  | 884/1147 [06:39<01:50,  2.37it/s]

Парсинг новостей:  77%|███████▋  | 885/1147 [06:40<01:50,  2.36it/s]

Парсинг новостей:  77%|███████▋  | 886/1147 [06:40<01:48,  2.40it/s]

Парсинг новостей:  77%|███████▋  | 887/1147 [06:40<01:44,  2.49it/s]

Парсинг новостей:  77%|███████▋  | 888/1147 [06:41<01:42,  2.52it/s]

Парсинг новостей:  78%|███████▊  | 889/1147 [06:41<02:12,  1.95it/s]

Парсинг новостей:  78%|███████▊  | 890/1147 [06:42<02:04,  2.06it/s]

Парсинг новостей:  78%|███████▊  | 891/1147 [06:42<02:01,  2.11it/s]

Парсинг новостей:  78%|███████▊  | 892/1147 [06:43<01:59,  2.14it/s]

Парсинг новостей:  78%|███████▊  | 893/1147 [06:43<01:57,  2.16it/s]

Парсинг новостей:  78%|███████▊  | 894/1147 [06:44<01:58,  2.13it/s]

Парсинг новостей:  78%|███████▊  | 895/1147 [06:44<01:52,  2.24it/s]

Парсинг новостей:  78%|███████▊  | 896/1147 [06:44<01:46,  2.35it/s]

Парсинг новостей:  78%|███████▊  | 897/1147 [06:45<01:43,  2.43it/s]

Парсинг новостей:  78%|███████▊  | 898/1147 [06:45<01:45,  2.36it/s]

Парсинг новостей:  78%|███████▊  | 899/1147 [06:46<01:48,  2.28it/s]

Парсинг новостей:  78%|███████▊  | 900/1147 [06:46<01:49,  2.25it/s]

Парсинг новостей:  79%|███████▊  | 901/1147 [06:47<01:43,  2.39it/s]

Парсинг новостей:  79%|███████▊  | 902/1147 [06:47<01:40,  2.43it/s]

Парсинг новостей:  79%|███████▊  | 903/1147 [06:47<01:44,  2.34it/s]

Парсинг новостей:  79%|███████▉  | 904/1147 [06:48<01:50,  2.20it/s]

Парсинг новостей:  79%|███████▉  | 905/1147 [06:48<01:54,  2.11it/s]

Парсинг новостей:  79%|███████▉  | 906/1147 [06:49<02:12,  1.82it/s]

Парсинг новостей:  79%|███████▉  | 907/1147 [06:50<02:06,  1.90it/s]

Парсинг новостей:  79%|███████▉  | 908/1147 [06:50<01:55,  2.07it/s]

Парсинг новостей:  79%|███████▉  | 909/1147 [06:51<01:54,  2.08it/s]

Парсинг новостей:  79%|███████▉  | 910/1147 [06:51<01:53,  2.09it/s]

Парсинг новостей:  79%|███████▉  | 911/1147 [06:51<01:45,  2.23it/s]

Парсинг новостей:  80%|███████▉  | 912/1147 [06:52<01:41,  2.31it/s]

Парсинг новостей:  80%|███████▉  | 913/1147 [06:52<01:39,  2.35it/s]

Парсинг новостей:  80%|███████▉  | 914/1147 [06:53<01:42,  2.27it/s]

Парсинг новостей:  80%|███████▉  | 915/1147 [06:53<01:45,  2.19it/s]

Парсинг новостей:  80%|███████▉  | 916/1147 [06:54<01:47,  2.15it/s]

Парсинг новостей:  80%|███████▉  | 917/1147 [06:54<01:51,  2.06it/s]

Парсинг новостей:  80%|████████  | 918/1147 [06:55<01:44,  2.20it/s]

Парсинг новостей:  80%|████████  | 919/1147 [06:55<01:58,  1.92it/s]

Парсинг новостей:  80%|████████  | 920/1147 [06:56<01:57,  1.93it/s]

Парсинг новостей:  80%|████████  | 921/1147 [06:56<01:49,  2.06it/s]

Парсинг новостей:  80%|████████  | 922/1147 [06:57<01:44,  2.15it/s]

Парсинг новостей:  80%|████████  | 923/1147 [06:57<02:01,  1.84it/s]

Парсинг новостей:  81%|████████  | 924/1147 [06:58<02:02,  1.82it/s]

Парсинг новостей:  81%|████████  | 925/1147 [06:58<01:56,  1.91it/s]

Парсинг новостей:  81%|████████  | 926/1147 [06:59<01:46,  2.07it/s]

Парсинг новостей:  81%|████████  | 927/1147 [06:59<01:42,  2.14it/s]

Парсинг новостей:  81%|████████  | 928/1147 [07:00<01:36,  2.28it/s]

Парсинг новостей:  81%|████████  | 929/1147 [07:00<01:36,  2.26it/s]

Парсинг новостей:  81%|████████  | 930/1147 [07:00<01:38,  2.21it/s]

Парсинг новостей:  81%|████████  | 931/1147 [07:01<01:31,  2.35it/s]

Парсинг новостей:  81%|████████▏ | 932/1147 [07:01<01:30,  2.37it/s]

Парсинг новостей:  81%|████████▏ | 933/1147 [07:02<01:29,  2.40it/s]

Парсинг новостей:  81%|████████▏ | 934/1147 [07:02<01:33,  2.29it/s]

Парсинг новостей:  82%|████████▏ | 935/1147 [07:03<01:37,  2.17it/s]

Парсинг новостей:  82%|████████▏ | 936/1147 [07:03<01:36,  2.20it/s]

Парсинг новостей:  82%|████████▏ | 937/1147 [07:04<01:33,  2.25it/s]

Парсинг новостей:  82%|████████▏ | 938/1147 [07:04<01:48,  1.93it/s]

Парсинг новостей:  82%|████████▏ | 939/1147 [07:05<01:47,  1.93it/s]

Парсинг новостей:  82%|████████▏ | 940/1147 [07:05<01:48,  1.91it/s]

Парсинг новостей:  82%|████████▏ | 941/1147 [07:06<01:46,  1.93it/s]

Парсинг новостей:  82%|████████▏ | 942/1147 [07:06<01:37,  2.10it/s]

Парсинг новостей:  82%|████████▏ | 943/1147 [07:07<01:32,  2.21it/s]

Парсинг новостей:  82%|████████▏ | 944/1147 [07:07<01:27,  2.32it/s]

Парсинг новостей:  82%|████████▏ | 945/1147 [07:07<01:29,  2.25it/s]

Парсинг новостей:  82%|████████▏ | 946/1147 [07:08<01:30,  2.22it/s]

Парсинг новостей:  83%|████████▎ | 947/1147 [07:08<01:31,  2.18it/s]

Парсинг новостей:  83%|████████▎ | 948/1147 [07:09<01:29,  2.23it/s]

Парсинг новостей:  83%|████████▎ | 949/1147 [07:09<01:30,  2.18it/s]

Парсинг новостей:  83%|████████▎ | 950/1147 [07:10<01:32,  2.13it/s]

Парсинг новостей:  83%|████████▎ | 951/1147 [07:10<01:28,  2.22it/s]

Парсинг новостей:  83%|████████▎ | 952/1147 [07:11<01:26,  2.24it/s]

Парсинг новостей:  83%|████████▎ | 953/1147 [07:11<01:23,  2.31it/s]

Парсинг новостей:  83%|████████▎ | 954/1147 [07:11<01:20,  2.39it/s]

Парсинг новостей:  83%|████████▎ | 955/1147 [07:12<01:19,  2.41it/s]

Парсинг новостей:  83%|████████▎ | 956/1147 [07:12<01:17,  2.46it/s]

Парсинг новостей:  83%|████████▎ | 957/1147 [07:13<01:20,  2.37it/s]

Парсинг новостей:  84%|████████▎ | 958/1147 [07:13<01:22,  2.29it/s]

Парсинг новостей:  84%|████████▎ | 959/1147 [07:13<01:19,  2.36it/s]

Парсинг новостей:  84%|████████▎ | 960/1147 [07:14<01:16,  2.45it/s]

Парсинг новостей:  84%|████████▍ | 961/1147 [07:14<01:15,  2.47it/s]

Парсинг новостей:  84%|████████▍ | 962/1147 [07:15<01:14,  2.48it/s]

Парсинг новостей:  84%|████████▍ | 963/1147 [07:15<01:11,  2.56it/s]

Парсинг новостей:  84%|████████▍ | 964/1147 [07:15<01:12,  2.53it/s]

Парсинг новостей:  84%|████████▍ | 965/1147 [07:16<01:12,  2.51it/s]

Парсинг новостей:  84%|████████▍ | 966/1147 [07:16<01:16,  2.36it/s]

Парсинг новостей:  84%|████████▍ | 967/1147 [07:17<01:18,  2.30it/s]

Парсинг новостей:  84%|████████▍ | 968/1147 [07:17<01:20,  2.23it/s]

Парсинг новостей:  84%|████████▍ | 969/1147 [07:18<01:30,  1.96it/s]

Парсинг новостей:  85%|████████▍ | 970/1147 [07:18<01:27,  2.03it/s]

Парсинг новостей:  85%|████████▍ | 971/1147 [07:19<01:25,  2.06it/s]

Парсинг новостей:  85%|████████▍ | 972/1147 [07:19<01:19,  2.21it/s]

Парсинг новостей:  85%|████████▍ | 973/1147 [07:20<01:14,  2.34it/s]

Парсинг новостей:  85%|████████▍ | 974/1147 [07:20<01:13,  2.36it/s]

Парсинг новостей:  85%|████████▌ | 975/1147 [07:20<01:17,  2.21it/s]

Парсинг новостей:  85%|████████▌ | 976/1147 [07:21<01:17,  2.20it/s]

Парсинг новостей:  85%|████████▌ | 977/1147 [07:21<01:18,  2.17it/s]

Парсинг новостей:  85%|████████▌ | 978/1147 [07:22<01:16,  2.21it/s]

Парсинг новостей:  85%|████████▌ | 979/1147 [07:22<01:14,  2.27it/s]

Парсинг новостей:  85%|████████▌ | 980/1147 [07:23<01:15,  2.22it/s]

Парсинг новостей:  86%|████████▌ | 981/1147 [07:23<01:12,  2.28it/s]

Парсинг новостей:  86%|████████▌ | 982/1147 [07:24<01:15,  2.20it/s]

Парсинг новостей:  86%|████████▌ | 983/1147 [07:24<01:13,  2.25it/s]

Парсинг новостей:  86%|████████▌ | 984/1147 [07:24<01:08,  2.37it/s]

Парсинг новостей:  86%|████████▌ | 985/1147 [07:25<01:06,  2.45it/s]

Парсинг новостей:  86%|████████▌ | 986/1147 [07:25<01:05,  2.46it/s]

Парсинг новостей:  86%|████████▌ | 987/1147 [07:26<01:06,  2.39it/s]

Парсинг новостей:  86%|████████▌ | 988/1147 [07:26<01:09,  2.28it/s]

Парсинг новостей:  86%|████████▌ | 989/1147 [07:27<01:06,  2.39it/s]

Парсинг новостей:  86%|████████▋ | 990/1147 [07:27<01:04,  2.45it/s]

Парсинг новостей:  86%|████████▋ | 991/1147 [07:27<01:02,  2.50it/s]

Парсинг новостей:  86%|████████▋ | 992/1147 [07:28<01:04,  2.39it/s]

Парсинг новостей:  87%|████████▋ | 993/1147 [07:28<01:03,  2.43it/s]

Парсинг новостей:  87%|████████▋ | 994/1147 [07:29<01:01,  2.47it/s]

Парсинг новостей:  87%|████████▋ | 995/1147 [07:29<01:01,  2.46it/s]

Парсинг новостей:  87%|████████▋ | 996/1147 [07:29<01:02,  2.41it/s]

Парсинг новостей:  87%|████████▋ | 997/1147 [07:30<01:03,  2.35it/s]

Парсинг новостей:  87%|████████▋ | 998/1147 [07:30<01:01,  2.41it/s]

Парсинг новостей:  87%|████████▋ | 999/1147 [07:31<01:00,  2.46it/s]

Парсинг новостей:  87%|███████▊ | 1000/1147 [07:31<01:01,  2.38it/s]

Парсинг новостей:  87%|███████▊ | 1001/1147 [07:31<01:00,  2.40it/s]

Парсинг новостей:  87%|███████▊ | 1002/1147 [07:32<01:02,  2.31it/s]

Парсинг новостей:  87%|███████▊ | 1003/1147 [07:32<00:59,  2.40it/s]

Парсинг новостей:  88%|███████▉ | 1004/1147 [07:33<00:57,  2.50it/s]

Парсинг новостей:  88%|███████▉ | 1005/1147 [07:33<00:56,  2.50it/s]

Парсинг новостей:  88%|███████▉ | 1006/1147 [07:34<00:58,  2.41it/s]

Парсинг новостей:  88%|███████▉ | 1007/1147 [07:34<00:56,  2.47it/s]

Парсинг новостей:  88%|███████▉ | 1008/1147 [07:34<00:54,  2.53it/s]

Парсинг новостей:  88%|███████▉ | 1009/1147 [07:35<00:53,  2.58it/s]

Парсинг новостей:  88%|███████▉ | 1010/1147 [07:35<00:55,  2.45it/s]

Парсинг новостей:  88%|███████▉ | 1011/1147 [07:36<00:58,  2.34it/s]

Парсинг новостей:  88%|███████▉ | 1012/1147 [07:36<00:55,  2.41it/s]

Парсинг новостей:  88%|███████▉ | 1013/1147 [07:36<00:57,  2.33it/s]

Парсинг новостей:  88%|███████▉ | 1014/1147 [07:37<00:55,  2.39it/s]

Парсинг новостей:  88%|███████▉ | 1015/1147 [07:37<00:57,  2.31it/s]

Парсинг новостей:  89%|███████▉ | 1016/1147 [07:38<00:55,  2.35it/s]

Парсинг новостей:  89%|███████▉ | 1017/1147 [07:38<00:54,  2.41it/s]

Парсинг новостей:  89%|███████▉ | 1018/1147 [07:39<00:53,  2.40it/s]

Парсинг новостей:  89%|███████▉ | 1019/1147 [07:39<00:52,  2.45it/s]

Парсинг новостей:  89%|████████ | 1020/1147 [07:39<00:55,  2.28it/s]

Парсинг новостей:  89%|████████ | 1021/1147 [07:40<00:56,  2.23it/s]

Парсинг новостей:  89%|████████ | 1022/1147 [07:40<00:56,  2.20it/s]

Парсинг новостей:  89%|████████ | 1023/1147 [07:41<00:57,  2.16it/s]

Парсинг новостей:  89%|████████ | 1024/1147 [07:41<00:53,  2.28it/s]

Парсинг новостей:  89%|████████ | 1025/1147 [07:42<00:56,  2.18it/s]

Парсинг новостей:  89%|████████ | 1026/1147 [07:42<00:53,  2.28it/s]

Парсинг новостей:  90%|████████ | 1027/1147 [07:42<00:50,  2.37it/s]

Парсинг новостей:  90%|████████ | 1028/1147 [07:43<00:51,  2.29it/s]

Парсинг новостей:  90%|████████ | 1029/1147 [07:43<00:49,  2.37it/s]

Парсинг новостей:  90%|████████ | 1030/1147 [07:44<00:47,  2.44it/s]

Парсинг новостей:  90%|████████ | 1031/1147 [07:44<00:47,  2.43it/s]

Парсинг новостей:  90%|████████ | 1032/1147 [07:45<00:50,  2.30it/s]

Парсинг новостей:  90%|████████ | 1033/1147 [07:45<00:48,  2.33it/s]

Парсинг новостей:  90%|████████ | 1034/1147 [07:45<00:46,  2.44it/s]

Парсинг новостей:  90%|████████ | 1035/1147 [07:46<00:46,  2.39it/s]

Парсинг новостей:  90%|████████▏| 1036/1147 [07:46<00:46,  2.38it/s]

Парсинг новостей:  90%|████████▏| 1037/1147 [07:47<00:55,  1.98it/s]

Парсинг новостей:  90%|████████▏| 1038/1147 [07:47<00:51,  2.13it/s]

Парсинг новостей:  91%|████████▏| 1039/1147 [07:48<00:48,  2.24it/s]

Парсинг новостей:  91%|████████▏| 1040/1147 [07:48<00:48,  2.21it/s]

Парсинг новостей:  91%|████████▏| 1041/1147 [07:49<00:48,  2.18it/s]

Парсинг новостей:  91%|████████▏| 1042/1147 [07:49<00:46,  2.27it/s]

Парсинг новостей:  91%|████████▏| 1043/1147 [07:49<00:44,  2.35it/s]

Парсинг новостей:  91%|████████▏| 1044/1147 [07:50<00:42,  2.41it/s]

Парсинг новостей:  91%|████████▏| 1045/1147 [07:50<00:42,  2.43it/s]

Парсинг новостей:  91%|████████▏| 1046/1147 [07:51<00:40,  2.48it/s]

Парсинг новостей:  91%|████████▏| 1047/1147 [07:51<00:40,  2.50it/s]

Парсинг новостей:  91%|████████▏| 1048/1147 [07:51<00:39,  2.52it/s]

Парсинг новостей:  91%|████████▏| 1049/1147 [07:52<00:47,  2.08it/s]

Парсинг новостей:  92%|████████▏| 1050/1147 [07:53<00:47,  2.03it/s]

Парсинг новостей:  92%|████████▏| 1051/1147 [07:53<00:45,  2.10it/s]

Парсинг новостей:  92%|████████▎| 1052/1147 [07:54<00:44,  2.13it/s]

Парсинг новостей:  92%|████████▎| 1053/1147 [07:54<00:42,  2.19it/s]

Парсинг новостей:  92%|████████▎| 1054/1147 [07:54<00:40,  2.29it/s]

Парсинг новостей:  92%|████████▎| 1055/1147 [07:55<00:38,  2.38it/s]

Парсинг новостей:  92%|████████▎| 1056/1147 [07:55<00:37,  2.40it/s]

Парсинг новостей:  92%|████████▎| 1057/1147 [07:56<00:39,  2.30it/s]

Парсинг новостей:  92%|████████▎| 1058/1147 [07:56<00:38,  2.28it/s]

Парсинг новостей:  92%|████████▎| 1059/1147 [07:56<00:37,  2.36it/s]

Парсинг новостей:  92%|████████▎| 1060/1147 [07:57<00:36,  2.39it/s]

Парсинг новостей:  93%|████████▎| 1061/1147 [07:57<00:35,  2.45it/s]

Парсинг новостей:  93%|████████▎| 1062/1147 [07:58<00:36,  2.31it/s]

Парсинг новостей:  93%|████████▎| 1063/1147 [07:58<00:36,  2.32it/s]

Парсинг новостей:  93%|████████▎| 1064/1147 [07:59<00:34,  2.39it/s]

Парсинг новостей:  93%|████████▎| 1065/1147 [07:59<00:33,  2.44it/s]

Парсинг новостей:  93%|████████▎| 1066/1147 [07:59<00:32,  2.46it/s]

Парсинг новостей:  93%|████████▎| 1067/1147 [08:00<00:33,  2.36it/s]

Парсинг новостей:  93%|████████▍| 1068/1147 [08:00<00:34,  2.31it/s]

Парсинг новостей:  93%|████████▍| 1069/1147 [08:01<00:35,  2.22it/s]

Парсинг новостей:  93%|████████▍| 1070/1147 [08:01<00:33,  2.28it/s]

Парсинг новостей:  93%|████████▍| 1071/1147 [08:02<00:32,  2.33it/s]

Парсинг новостей:  93%|████████▍| 1072/1147 [08:02<00:31,  2.40it/s]

Парсинг новостей:  94%|████████▍| 1073/1147 [08:02<00:32,  2.26it/s]

Парсинг новостей:  94%|████████▍| 1074/1147 [08:03<00:31,  2.30it/s]

Парсинг новостей:  94%|████████▍| 1075/1147 [08:03<00:31,  2.25it/s]

Парсинг новостей:  94%|████████▍| 1076/1147 [08:04<00:29,  2.38it/s]

Парсинг новостей:  94%|████████▍| 1077/1147 [08:04<00:29,  2.38it/s]

Парсинг новостей:  94%|████████▍| 1078/1147 [08:05<00:28,  2.43it/s]

Парсинг новостей:  94%|████████▍| 1079/1147 [08:05<00:35,  1.90it/s]

Парсинг новостей:  94%|████████▍| 1080/1147 [08:06<00:32,  2.07it/s]

Парсинг новостей:  94%|████████▍| 1081/1147 [08:06<00:30,  2.15it/s]

Парсинг новостей:  94%|████████▍| 1082/1147 [08:07<00:30,  2.11it/s]

Парсинг новостей:  94%|████████▍| 1083/1147 [08:07<00:30,  2.12it/s]

Парсинг новостей:  95%|████████▌| 1084/1147 [08:07<00:28,  2.23it/s]

Парсинг новостей:  95%|████████▌| 1085/1147 [08:08<00:30,  2.00it/s]

Парсинг новостей:  95%|████████▌| 1086/1147 [08:08<00:28,  2.14it/s]

Парсинг новостей:  95%|████████▌| 1087/1147 [08:09<00:26,  2.26it/s]

Парсинг новостей:  95%|████████▌| 1088/1147 [08:09<00:25,  2.32it/s]

Парсинг новостей:  95%|████████▌| 1089/1147 [08:10<00:25,  2.29it/s]

Парсинг новостей:  95%|████████▌| 1090/1147 [08:10<00:25,  2.20it/s]

Парсинг новостей:  95%|████████▌| 1091/1147 [08:11<00:24,  2.30it/s]

Парсинг новостей:  95%|████████▌| 1092/1147 [08:11<00:24,  2.27it/s]

Парсинг новостей:  95%|████████▌| 1093/1147 [08:11<00:22,  2.35it/s]

Парсинг новостей:  95%|████████▌| 1094/1147 [08:12<00:26,  1.99it/s]

Парсинг новостей:  95%|████████▌| 1095/1147 [08:13<00:24,  2.11it/s]

Парсинг новостей:  96%|████████▌| 1096/1147 [08:13<00:22,  2.23it/s]

Парсинг новостей:  96%|████████▌| 1097/1147 [08:13<00:22,  2.25it/s]

Парсинг новостей:  96%|████████▌| 1098/1147 [08:14<00:22,  2.16it/s]

Парсинг новостей:  96%|████████▌| 1099/1147 [08:14<00:23,  2.05it/s]

Парсинг новостей:  96%|████████▋| 1100/1147 [08:15<00:24,  1.94it/s]

Парсинг новостей:  96%|████████▋| 1101/1147 [08:16<00:26,  1.71it/s]

Парсинг новостей:  96%|████████▋| 1102/1147 [08:16<00:23,  1.93it/s]

Парсинг новостей:  96%|████████▋| 1103/1147 [08:17<00:21,  2.02it/s]

Парсинг новостей:  96%|████████▋| 1104/1147 [08:17<00:20,  2.08it/s]

Парсинг новостей:  96%|████████▋| 1105/1147 [08:17<00:18,  2.23it/s]

Парсинг новостей:  96%|████████▋| 1106/1147 [08:18<00:17,  2.35it/s]

Парсинг новостей:  97%|████████▋| 1107/1147 [08:18<00:16,  2.42it/s]

Парсинг новостей:  97%|████████▋| 1108/1147 [08:19<00:16,  2.37it/s]

Парсинг новостей:  97%|████████▋| 1109/1147 [08:19<00:15,  2.45it/s]

Парсинг новостей:  97%|████████▋| 1110/1147 [08:19<00:14,  2.48it/s]

Парсинг новостей:  97%|████████▋| 1111/1147 [08:20<00:14,  2.55it/s]

Парсинг новостей:  97%|████████▋| 1112/1147 [08:20<00:14,  2.36it/s]

Парсинг новостей:  97%|████████▋| 1113/1147 [08:21<00:17,  1.93it/s]

Парсинг новостей:  97%|████████▋| 1114/1147 [08:21<00:15,  2.08it/s]

Парсинг новостей:  97%|████████▋| 1115/1147 [08:22<00:15,  2.11it/s]

Парсинг новостей:  97%|████████▊| 1116/1147 [08:22<00:14,  2.09it/s]

Парсинг новостей:  97%|████████▊| 1117/1147 [08:25<00:30,  1.01s/it]

Парсинг новостей:  97%|████████▊| 1118/1147 [08:25<00:24,  1.18it/s]

Парсинг новостей:  98%|████████▊| 1119/1147 [08:26<00:20,  1.34it/s]

Парсинг новостей:  98%|████████▊| 1120/1147 [08:26<00:17,  1.52it/s]

Парсинг новостей:  98%|████████▊| 1121/1147 [08:26<00:15,  1.66it/s]

Парсинг новостей:  98%|████████▊| 1122/1147 [08:27<00:13,  1.84it/s]

Парсинг новостей:  98%|████████▊| 1123/1147 [08:27<00:12,  1.96it/s]

Парсинг новостей:  98%|████████▊| 1124/1147 [08:28<00:11,  2.04it/s]

Парсинг новостей:  98%|████████▊| 1125/1147 [08:28<00:10,  2.02it/s]

Парсинг новостей:  98%|████████▊| 1126/1147 [08:29<00:09,  2.11it/s]

Парсинг новостей:  98%|████████▊| 1127/1147 [08:29<00:09,  2.14it/s]

Парсинг новостей:  98%|████████▊| 1128/1147 [08:30<00:08,  2.13it/s]

Парсинг новостей:  98%|████████▊| 1129/1147 [08:30<00:08,  2.20it/s]

Парсинг новостей:  99%|████████▊| 1130/1147 [08:30<00:07,  2.26it/s]

Парсинг новостей:  99%|████████▊| 1131/1147 [08:31<00:06,  2.37it/s]

Парсинг новостей:  99%|████████▉| 1132/1147 [08:31<00:06,  2.32it/s]

Парсинг новостей:  99%|████████▉| 1133/1147 [08:32<00:06,  2.25it/s]

Парсинг новостей:  99%|████████▉| 1134/1147 [08:32<00:05,  2.35it/s]

Парсинг новостей:  99%|████████▉| 1135/1147 [08:32<00:04,  2.44it/s]

Парсинг новостей:  99%|████████▉| 1136/1147 [08:33<00:04,  2.52it/s]

Парсинг новостей:  99%|████████▉| 1137/1147 [08:33<00:04,  2.45it/s]

Парсинг новостей:  99%|████████▉| 1138/1147 [08:34<00:03,  2.48it/s]

Парсинг новостей:  99%|████████▉| 1139/1147 [08:34<00:03,  2.46it/s]

Парсинг новостей:  99%|████████▉| 1140/1147 [08:34<00:02,  2.49it/s]

Парсинг новостей:  99%|████████▉| 1141/1147 [08:35<00:02,  2.43it/s]

Парсинг новостей: 100%|████████▉| 1142/1147 [08:35<00:02,  2.37it/s]

Парсинг новостей: 100%|████████▉| 1143/1147 [08:36<00:01,  2.44it/s]

Парсинг новостей: 100%|████████▉| 1144/1147 [08:36<00:01,  2.48it/s]

Парсинг новостей: 100%|████████▉| 1145/1147 [08:37<00:00,  2.49it/s]

Парсинг новостей: 100%|████████▉| 1146/1147 [08:37<00:00,  2.38it/s]

Парсинг новостей: 100%|█████████| 1147/1147 [08:37<00:00,  2.30it/s]

Парсинг новостей: 100%|█████████| 1147/1147 [08:37<00:00,  2.21it/s]

Всего сохранено статей: 1147
Ошибок этого запуска: 0

,id,title,date,views,text,tags,url
0,15033,Соединили пышки и квантовую механику: как ИТМО...,2026-09-21T18:24:25+03:00,122.0,"Более четырех тысяч километров, пять городов и...",Главное; Геймификация; Фестивали; Яндекс Образ...,https://news.itmo.ru/ru/education/cooperation/...
1,15018,Эра сверхбыстрых вычислений: в ИТМО появился И...,2026-09-15T16:40:38+03:00,1304.0,В 2026 году в Университете ИТМО появился Инсти...,Фотоника; Главное; Фотонные технологии; Главно...,https://news.itmo.ru/ru/science/photonics/news...
2,15003,Олимпиадный год: итоги самой масштабной приемн...,2026-09-01T19:18:10+03:00,7971.0,В ИТМО опубликованы все приказы о зачислении в...,Магистратура; Бакалавриат; Аспирантура; Главно...,https://news.itmo.ru/ru/education/official/new...
3,15001,ITMO CONF 2026: как идеи проходят путь от лабо...,2026-08-31T18:44:11+03:00,5976.0,Трансформация научной идеи в работающий продук...,Главное; Будущее образования; ГлавноеBottom; И...,https://news.itmo.ru/ru/education/trend/news/1...
4,14985,Всем по киберпышке! ИТМО и Яндекс Образование ...,2026-08-18T15:57:07+03:00,13128.0,Университет ИТМО и Яндекс Образование отправля...,Главное; Геймификация; Фестивали; Яндекс Образ...,https://news.itmo.ru/ru/education/cooperation/...

In [9]:
content_df.to_csv(
    CONTENT_CSV,
    index=False,
    encoding="utf-8"
)

print("Сохранено:", CONTENT_CSV.resolve())
print("Строк:", len(content_df))

Сохранено: /Users/infinitrator/infinitrator.github.io/lab8/news_content/news_content.csv
Строк: 1147

## 8. Проверка качества полученных данных

Проверяем:

- отсутствие повторяющихся идентификаторов;
- количество пропущенных значений;
- наличие текста;
- наличие просмотров;
- распределение длины текстов.

In [10]:
print("Размер датасета:", content_df.shape)
print()

print("Дубликаты ID:")
print(content_df["id"].duplicated().sum())
print()

print("Пропуски:")
display(content_df.isna().sum().to_frame("missing"))

if not content_df.empty:
    text_lengths = content_df["text"].fillna("").str.len()

    print()
    print("Длина текста:")
    display(text_lengths.describe().to_frame("characters"))

    print()
    print("Пример результата:")
    display(
        content_df[
            ["id", "title", "date", "views", "tags"]
        ].head()
    )

Размер датасета: (1147, 7)

Дубликаты ID:
0

Пропуски:

       missing
id           0
title        0
date         0
views      187
text         1
tags         0
url          0

Длина текста:

         characters
count   1147.000000
mean    6842.244987
std     4040.903099
min        0.000000
25%     3792.500000
50%     5983.000000
75%     9181.000000
max    29185.000000

Пример результата:

,id,title,date,views,tags
0,15033,Соединили пышки и квантовую механику: как ИТМО...,2026-09-21T18:24:25+03:00,122.0,Главное; Геймификация; Фестивали; Яндекс Образ...
1,15018,Эра сверхбыстрых вычислений: в ИТМО появился И...,2026-09-15T16:40:38+03:00,1304.0,Фотоника; Главное; Фотонные технологии; Главно...
2,15003,Олимпиадный год: итоги самой масштабной приемн...,2026-09-01T19:18:10+03:00,7971.0,Магистратура; Бакалавриат; Аспирантура; Главно...
3,15001,ITMO CONF 2026: как идеи проходят путь от лабо...,2026-08-31T18:44:11+03:00,5976.0,Главное; Будущее образования; ГлавноеBottom; И...
4,14985,Всем по киберпышке! ИТМО и Яндекс Образование ...,2026-08-18T15:57:07+03:00,13128.0,Главное; Геймификация; Фестивали; Яндекс Образ...

## Вывод

В работе реализован двухэтапный парсинг сайта ITMO.NEWS.

На первом этапе формируется общий список публикаций с идентификатором, названием, датой и URL. На втором этапе открывается страница каждой новости и извлекаются подробные данные: количество просмотров, текст и теги.

Полученные данные сохраняются в `news.csv` и `news_content/news_content.csv`. Парсер учитывает вариативность HTML-разметки текста и использует резервные селекторы при отсутствии основной структуры.